### ISSUE TITLE
Set the default column maximum width on the table

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#10136]
### In what scenarios do you need this feature?

现在思源笔记的表格有一个问题，直接往表格里粘贴长文本，表格的宽度默认会被拉的很长，想再拖回适当宽度很费劲
![思源表格默认粘贴长文本会有问题](https://github.com/siyuan-note/siyuan/assets/60436214/e376eab3-4ef4-4051-b27a-d35d6a8a28ea)

### Describe the optimal solution

我发现表格添加word-wrap和列max-width就能解决这个问题，并且max-width这个值只是影响粘贴文字时的最大列宽度，默认的表格宽度依然是60px，也依然可以调整表格的列宽度

```css
/* 表格文字换行 */
.protyle-wysiwyg div.table[data-node-id] table {
    word-wrap: break-word;
}
/* 设置表格每列默认宽度 */
.protyle-wysiwyg div.table[data-node-id] table tr td{
    max-width: 400px; 
}
```

![思源表格添加文本换行和设置表格列最大宽度](https://github.com/siyuan-note/siyuan/assets/60436214/9dbb4797-0e94-44a2-a96f-02493dea6406)

### Describe the candidate solution

none
