### ISSUE TITLE
There is a string of cloze in spaced repetition window

### ISSUE THREAD

**Issue by luo-chuan** [siyuan-note/siyuan#10315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如果标记中出现了带样式的文字，比如斜体、加粗、公式等：

![图片](https://github.com/siyuan-note/siyuan/assets/33930736/6ec24a5b-ecff-455b-9abc-1ac6d60ee562)

那间隔重复页面就会呈现出多个连续挖空：

![图片](https://github.com/siyuan-note/siyuan/assets/33930736/d15c52cc-6272-4d4c-a06b-8a18381b204c)

### Expected result

添加如下 CSS 代码片段即可解决问题：

```css
/* 合并卡片中的多个连续挖空 */
.card__block--hidemark span[data-type~=mark] + span[data-type~=mark]::before {
    display: none;
}
```

关联：https://ld246.com/article/1707068293972

### Version environment

```markdown
- Version: 2.12.6
- Operating System:  android
- Browser (if used): edge
```

### Log file

无
