### ISSUE TITLE
反链面板的字体大小可以自定义

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10680]
### In what scenarios do you need this feature?

这个功能的意义主要在于使用反链面板的时候，注重的是反链的哪些内容。

但是如果和编辑器字体大小一样的话，就不太好浏览，因为看反链面板有时候是要从一大堆里面找到需要的。
如果字体和编辑器大小一样的话，找起来就比较缓慢，而且视觉上也没有和编辑器区分开来

![image](https://github.com/siyuan-note/siyuan/assets/62794181/ccb9034f-36be-4bad-95d5-fa3e83569d1b)

### Describe the optimal solution

希望能够自定义反链面板的字体大小

**Comment by 5kyfkr** [comment]
支持，反链面板的字太大了，在侧栏很难快速浏览

**Comment by 88250** [comment]
应该可以通过自定义 CSS 实现。原生状态下我支持调整小一点 @Vanessa219

**Comment by Vanessa219** [comment]
缩小后行高等都会有问题，建议使用 css 代码片段调整到自己觉得最舒适的大小。
```
.sy__backlink .protyle-wysiwyg {
}
```

**Comment by QQQOrange** [comment]
> .sy__backlink .protyle-wysiwyg {
> }

.sy__backlink .protyle-wysiwyg {font-size:12px;
}
请问具体该怎么用呢？我设置成这样，但是面板里面没有任何变化

**Comment by 5kyfkr** [comment]
> > .sy__backlink .protyle-wysiwyg {
> > }
> 
> .sy__backlink .protyle-wysiwyg {font-size:12px; } 请问具体该怎么用呢？我设置成这样，但是面板里面没有任何变化

.sy__backlink .protyle-wysiwyg {
font-size: 16px !important;
}
我是这样的，加个!important就行了

**Comment by TCOTC** [comment]
如果用 font-size ，界面中的其他元素不会变，会有偏移，就很别扭。

用 transform: scale(0.8) 的话整个界面都缩小了，边距又变大，还是不行。

谁能给个好用的 CSS 片段？

**Comment by QQQOrange** [comment]
> > > .sy__backlink .protyle-wysiwyg {
> > > }
> > 
> > .sy__backlink .protyle-wysiwyg {font-size:12px; } 请问具体该怎么用呢？我设置成这样，但是面板里面没有任何变化
> 
> .sy__backlink .protyle-wysiwyg {
> font-size: 16px !important;
> }
> 我是这样的，加个!important就行了

！！谢谢谢谢谢谢

**Comment by QQQOrange** [comment]
> 如果用 font-size ，界面中的其他元素不会变，会有偏移，就很别扭。
> 
> 用 transform: scale(0.8) 的话整个界面都缩小了，边距又变大，还是不行。
> 
> 谁能给个好用的 CSS 片段？

同求同求

**Comment by Vanessa219** [comment]
缩放的话估计没有办法

**Comment by TCOTC** [comment]
我又想到了，现在可以了：

```css
/* 改变反链区域字体大小 CSS片段 */
.sy__backlink .backlinkList .b3-list {
    transform: scale(0.8); /* 缩放比例可以根据需要调整 */
    transform-origin: 0 0; /* 设置缩放的原点为左上角 */
    width: 125%; /* 1 / 0.8 = 1.25，根据缩放比例调整宽度 */
    overflow-x: hidden; /* 避免出现横向滚动条 */
    overflow-y: hidden; /* 避免出现纵向滚动条 */
}
.sy__backlink .backlinkMList .b3-list {
    transform: scale(0.8); /* 缩放比例可以根据需要调整 */
    transform-origin: 0 0; /* 设置缩放的原点为左上角 */
    width: 125%; /* 1 / 0.8 = 1.25，根据缩放比例调整宽度 */
    overflow-x: hidden; /* 避免出现横向滚动条 */
    overflow-y: hidden; /* 避免出现纵向滚动条 */
}
.sy__backlink .backlinkList,
.sy__backlink .backlinkMList {
    overflow-x: hidden; /* 避免出现横向滚动条 */
}
```

@QQQOrange
