### ISSUE TITLE
添加一种让双链在正文中具有割裂感的「双链显示类型」

### ISSUE THREAD

**Issue by edward-kyle** [siyuan-note/siyuan#10708]
### In what scenarios do you need this feature?

添加一种让双链和正文具有割裂感的显示类型。
例如：#双链，@双链，&双链

### Describe the optimal solution

需要另外一种双链显示样式，以达到能够与正文割裂开的效果。
传递型双链可以代替标签的功能，却没有标签带来的视觉冲击感。
在某些情况下，需要这种类似标签的双链显示形式。

关联：
https://ld246.com/article/1690702712149

### Describe the candidate solution

过渡方案1：
![image](https://github.com/siyuan-note/siyuan/assets/78415230/a68b8c21-7fcd-41e6-a023-04cdf079ad35)
和转换为 " * " 是一个道理，无非就是双链的一个特定的显示格式而已。
在右键双链的菜单项目 “转换为” 里面添加一个选项，把双链的格式转换成 “# 动态锚文本”，或“@ 动态锚文本”，或“& 动态锚文本”。然后实际处理的时候就固定在锚文本前面加上一个 "#"，"@"，或"&"。

但是这种方案使用成本好像会更高。

过渡方案2:
用户为“双链”设置一个别名——“#双链”。
可通过【【#双链，搜索到“#双链”。然后在笔记中，双链显示为：#双链

**Comment by edward-kyle** [comment]
这个issue可能优先级不高，只是打开放在这里。
D大还是按照自己的开发计划来开发

**Comment by QQQOrange** [comment]
这个和页面反链是一个意思吗？也即是在当前的页面下面显示反链所应用的地方

**Comment by gdy106** [comment]
可用“思源增强器”这个插件顶一下，让双链文本前后加[[文本]]

**Comment by TCOTC** [comment]
> 在右键双链的菜单项目 “转换为” 里面添加一个选项，把双链的格式转换成 “# 动态锚文本”，或“@ 动态锚文本”，或“& 动态锚文本”。然后实际处理的时候就固定在锚文本前面加上一个 "#"，"@"，或"&"。

我感觉这个好像没法简单地实现，动态静态锚文本也只是通过 `'` 和 `"` 来区分。

静态锚文本的块引用一般在文段中使用，有连贯的上下文，我的建议是只给动态锚文本的块引用使用这种样式：

```css
/* 块引用动态锚文本 CSS */
.protyle-wysiwyg span[data-type="block-ref"][data-subtype="d"] {
	border-radius: 3px;
	padding:0px 3px 0px 3px;
	background-color:var(--b3-font-background7);
}
.protyle-wysiwyg span[data-type="block-ref"][data-subtype="d"]::before{
	content: "@";
}
.export-img span[data-type="block-ref"][data-subtype="d"]::before{
	content: "";
}
```

![image](https://github.com/user-attachments/assets/f618d81b-4b22-4e5f-ab7b-db2984dd6668)
