### ISSUE TITLE
Update the dom of code blocks

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10769]
把全部行号和全部代码用一个父节点包裹

### In what scenarios do you need this feature?

01

```css
.protyle-wysiwyg div.code-block[data-node-id] {
    overflow-y: auto;
    max-height: 20vh;
}

.protyle-linenumber, .protyle-linenumber__rows{
    height:100%;
}
```

用这个CSS片段之后，书签之类的就在滚动容器中被遮盖了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/63edcaa2-32ca-4f97-904f-49f7483602de)

02

```css
.protyle-wysiwyg div.code-block[data-node-id] .hljs {
    overflow-y: auto;
    max-height: 20vh;
}
.protyle-linenumber, .protyle-linenumber__rows{
    height:100%;
}
```

用这个CSS片段之后，书签之类的能显示了，但代码块行号又不能跟随着滚动了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e5bd10f3-1dcd-462e-8f56-3e5e86a9896b)

### Describe the optimal solution

# 有什么办法让代码块行号和书签之类的都能正常显示呢？

### Other information

https://ld246.com/article/1699238495421

**Comment by Vanessa219** [comment]
行号和代码块是分离的，好像不行。估计要弄点 js 之类的吧。

**Comment by TCOTC** [comment]
@Vanessa219 要不当开启代码块行号的时候就把行号和代码套在一个 <div> 标签里？现在的问题我个人解决不了

**Comment by Vanessa219** [comment]
这个用的是 highlight.js，好像没有办法去支持。

**Comment by TCOTC** [comment]
我看到 highlight.js 原生不支持行号：

https://github.com/highlightjs/highlight.js/blob/main/docs/line-numbers.rst

**Comment by TCOTC** [comment]
有道理，不过这个代码片段用了之后同时开启代码块行号和代码块换行就会有问题

![image](https://github.com/siyuan-note/siyuan/assets/78434827/fd460b36-7ff9-44c4-9ca0-b53bac49ddcb)

**Comment by Achuan-2** [comment]
试试这个
```css
.protyle-wysiwyg .code-block{
    max-height: 800px;
    overflow: auto;
    padding-top: 10px;
}
.protyle-wysiwyg .hljs,
.protyle-linenumber__rows{
    height:max-content;
}
.protyle-wysiwyg .code-block .protyle-attr {
    top: -2px;
}
```

**Comment by Achuan-2** [comment]
忽略了复制按钮的悬浮文字提示，再改改
```css
.protyle-wysiwyg .hljs,
.protyle-linenumber__rows{
    height:max-content;
    margin-top: 10px;
}
.protyle-wysiwyg .code-block .protyle-attr {
    top: -2px;
}

.protyle-wysiwyg .code-block .protyle-action .b3-tooltips__nw {
    top: 25px;
}
.protyle-action .protyle-action__language{
    margin-top: 10px;
}
```

**Comment by TCOTC** [comment]
@Vanessa219 

![image](https://github.com/siyuan-note/siyuan/assets/78434827/8843f3e4-b504-4acf-8b11-699188778477)

**Comment by Vanessa219** [comment]
改了结果就没有办法渲染代码高亮了。

**Comment by Achuan-2** [comment]
> 改了结构就没有办法渲染代码高亮了。
用开发者工具改了下好像也没啥影响呀
![Clip_2024-05-13_11-48-42](https://github.com/siyuan-note/siyuan/assets/60436214/19f0b7bd-370f-4a40-90e3-f9cec908bdba)

**Comment by Vanessa219** [comment]
应该说的不是这样改。。。

**Comment by TCOTC** [comment]
@Vanessa219 「把行号和代码用一个父节点包裹在一起」就是这个意思

**Comment by Vanessa219** [comment]
改了看看吧，我觉得这样可能会有问题。

**Comment by TCOTC** [comment]
@Vanessa219 这个改了吗？

**Comment by Vanessa219** [comment]
这个 hljs 不支持，没法改。要一个行号和一行代码在一个div 里面才可以实现吧。

**Comment by TCOTC** [comment]
不用每一行，整个行号的元素和整个代码的元素包在一起就行了

**Comment by Vanessa219** [comment]
那怎么滚动呢？

**Comment by TCOTC** [comment]
这样就不能滚动了吗？

**Comment by Achuan-2** [comment]
代码块限制高度这一点可以参考语雀
![Clip_2024-08-09_18-56-18](https://github.com/user-attachments/assets/f0d38227-6224-49c3-b816-c8ee6762cd38)

在开发者工具输入下面代码，可以实现代码块限制高度后，代码块和行号能同时滚动了（不过因为改了dom，代码块修改内容会有问题，仅作演示用）
```js
        document.querySelectorAll('.code-block>div.hljs').forEach((hljsDiv) => {
            hljsDiv.style = "overflow: visible;";
            hljsDiv.style.backgroundColor = 'transparent';

            // 创建一个新的父容器，用于包裹 hljs.protyle-linenumber 和 protyle-linenumber__rows
            const scrollContainer = document.createElement('div');
            scrollContainer.style = 'display: flex; overflow: auto; max-height: 800px;';
            scrollContainer.style.justifyContent = 'flex-start';  // 子元素居左排列
            scrollContainer.style.alignItems = 'flex-start';      // 垂直方向上居左（顶部）

            // 查找 span.protyle-linenumber__rows 兄弟节点
            const siblingSpan = hljsDiv.nextElementSibling;
            if (siblingSpan && siblingSpan.classList.contains('protyle-linenumber__rows')) {
                // 将 span.protyle-linenumber__rows 移动到 scrollContainer 中
                siblingSpan.style.backgroundColor = 'transparent';
                scrollContainer.appendChild(siblingSpan.cloneNode(true));
                // 移除旧的 span.protyle-linenumber__rows
                siblingSpan.remove();
            }
            scrollContainer.appendChild(hljsDiv.cloneNode(true));

            // 将 scrollContainer 插入到原始的父容器中
            hljsDiv.parentNode.style = "flex-direction: row;"
            hljsDiv.parentNode.insertBefore(scrollContainer, hljsDiv);

            // 移除旧的 hljsDiv
            hljsDiv.remove();

        });
```

![思源文档代码块设置最大高度](https://github.com/user-attachments/assets/62dc387f-7d72-43cd-b7aa-e45a69dad872)

备注：默认主题的代码块内容和代码行号有设置背景色，但是父节点设置overflow:auto之后，设置的背景色只有设置的max-height高度，后面的滚动内容没有背景色，不过对于我的Tsundoku主题，本身就将其代码块内容和行号设置为透明色，用code-block来设置代码块的颜色，所以没有影响。

**Comment by Vanessa219** [comment]
哦，我大概明白了。

**Comment by Achuan-2** [comment]
想问问能否适配粘贴后的滚动高度呢？
之前的DOM结构，如果我自己在代码片段里设置代码块max-height，粘贴代码后，滚动高度依然会是原代码块高度，所以还需要上滚到代码块的实际位置

**Comment by Vanessa219** [comment]
指的是粘贴后需要滚动到光标位置么？

**Comment by Achuan-2** [comment]
> 指的是粘贴后需要滚动到光标位置么？

是的，这是现在的DOM结构限制代码块高度，在代码块粘贴的问题（注意：要复现代码块后面要有很多块）
![思源笔记代码块限制高度](https://github.com/user-attachments/assets/ba95c551-8df7-4dcc-aaa9-b72210ffac48)

**Comment by TCOTC** [comment]
感觉不错

```css
.protyle-wysiwyg .code-block > .hljs {
    max-height: 400px;
}
```

使用代码片段后的效果：

![image](https://github.com/user-attachments/assets/4ef8e0ab-d5b5-41e7-8b6e-c977c765201e)

**Comment by Misuzu2027** [comment]
@Vanessa219   v3.1.4-dev4 版本，代码块显示行号后，在代码块的菜单栏设置为不显示行号，切换后没有动态隐藏行号。

**Comment by TCOTC** [comment]
@Misuzu2027 #12268

**Comment by Achuan-2** [comment]
发现用了自定义css片段折叠代码块后存在一些问题
```css
div:not(#preview) > .protyle-wysiwyg .code-block .hljs {
    max-height: 300px;
}

```
在不开启行号的情况下，经过一定行后，直接在末尾按enter，不会创建新行，只有先打几个字，在中间按enter才能创建新行
在开启行号的情况下，经过按enter一直能创建新行，但可视区域不会自动移到下一行，需要手动滚动
希望：不开启行号的情况下，直接在末尾按enter，能创建新行，并且可视区域能自动移动到新创建的代码块行
