### ISSUE TITLE
字体加粗CSS代码排除PDF文档

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#10902]
### In what scenarios do you need this feature?

如下图，应用了下方css片段后，PDF界面的字体渲染不正常，有没办法在PDF里禁用？我不太清楚pdf的字体class是哪个，尝试了改不了，请求帮助
:not([class*="icon"]):not([class*="button"]):not([class*=mjx]):not([class*=fa]):not(i) {
 font-family: "HarmonyOS Sans SC Medium" !important;    /* 如果没有使用自定义字体插件需使用此行代码控制字体  */
    text-shadow: 0.01em 0.01em 0.01em #000 !important;  
}
body {
    -webkit-text-stroke-width: 0.01px;
    -webkit-font-smoothing: antialiased;
    text-rendering: geometricPrecision;
}

![image](https://github.com/siyuan-note/siyuan/assets/63196026/ba9181ed-839b-429a-8c63-429034807186)

### Describe the optimal solution

如题，字体能不在PDF渲染

**Comment by zxhd863943427** [comment]
在全部css片段前加 .protyle-wysiwyg 试试

**Comment by 5kyfkr** [comment]
> 在全部css片段前加 .protyle-wysiwyg 试试

可以的，但是好像除了编辑器，主界面侧边栏和文档树等的字体不在这范围里

**Comment by 5kyfkr** [comment]
就这样吧，复制两遍够用了

.protyle-wysiwyg{
:not([class*="icon"]):not([class*="button"]):not([class*=mjx]):not([class*=fa]):not(i){
 /*使修改字体不会应用于部分特殊字符符号和图标以及按钮等网页元素.*/
 /*  font-family: "HarmonyOS Sans SC Medium" !important;    如果没有使用自定义字体插件需使用此行代码控制字体 */
    text-shadow: 0.01em 0.01em 0.01em #000 !important;   /*更改字体阴影及透明度,可修改数值实现不同的效果.*/
}
body {
    -webkit-text-stroke-width: 0.01px;
    -webkit-font-smoothing: antialiased;
    text-rendering: geometricPrecision;
    /* text-rendering: geometricPrecision; */
}
}

.b3-list-item{:not([class*="icon"])
{
 /*使修改字体不会应用于部分特殊字符符号和图标以及按钮等网页元素.*/
 /*  font-family: "HarmonyOS Sans SC Medium" !important;    如果没有使用自定义字体插件需使用此行代码控制字体 */
    text-shadow: 0.01em 0.01em 0.01em #000 !important;   /*更改字体阴影及透明度,可修改数值实现不同的效果.*/
}
body {
    -webkit-text-stroke-width: 0.01px;
    -webkit-font-smoothing: antialiased;
    text-rendering: geometricPrecision;
    /* text-rendering: geometricPrecision; */
}
}

**Comment by 5kyfkr** [comment]
@88250 D大，移动端用这个.protyle-wysiwyg改不了编辑器内字体，是应该用哪个？

**Comment by 88250** [comment]
前端问题麻烦 @Vanessa219

**Comment by 5kyfkr** [comment]
@Vanessa219 V姐，移动端用这个.protyle-wysiwyg改不了编辑器内字体，是应该用哪个？还有PDF里的字体是哪个类也想了解一下？

**Comment by 5kyfkr** [comment]
搞定了，还是反向设置方便，直接把PDF的字体阴影设置成透明就好了
```css
:not([class*="icon"]):not([class*="button"]){
 /*使修改字体不会应用于部分特殊字符符号和图标以及按钮等网页元素.*/
    text-shadow: 0.01em 0.01em 0.01em #999999 ;  
 /*更改字体阴影及透明度,可修改数值实现不同的效果.*/
    -webkit-text-stroke-width: 0.10px;
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
}

.textLayer span
{
    text-shadow: 0.01em 0.01em 0.01em rgba(0,0,0,0) !important;  
}

.b3-typography strong, .b3-typography span[data-type~=strong], .protyle-wysiwyg strong, .protyle-wysiwyg span[data-type~=strong] {
    text-shadow: 0.01em 0.01em 0.01em #999999 !important;  
    -webkit-text-stroke-width: 0px !important;
}
```
