### ISSUE TITLE
Support setting height for some blocks

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11055]
代码块、嵌入块等块支持固定高度

### In what scenarios do you need this feature?

[一个想法：思源关于比较长的块，是否可以默认折叠，只显示前几行？ - 链滴](https://ld246.com/article/1713253762905)

有时候代码太长，不折叠的话要翻半天，折叠的话内容就都看不到了，希望有个功能像「固定表头」那样让块的高度显示为页面的一半。

还有嵌入块也是。

~~目前单纯用 CSS 做不了~~ 更新：代码块的已经有办法用 CSS 实现了 #10769 

### Describe the optimal solution

比如固定表头可以让表格的高度显示为页面的一半

```css
.protyle-wysiwyg [data-node-id].table[custom-pinthead=true] table {
    max-height: 50vh;
}
```

比如图表可以设置高度：

![image](https://github.com/user-attachments/assets/54ae3202-f793-4232-b65e-7a006d95fd5a)

**Comment by 88250** [comment]
完全没有的较大改进算作特性。

**Comment by TCOTC** [comment]
参考 Wolai 的代码块：

[video.webm](https://github.com/user-attachments/assets/11d6436b-188b-42ba-acb6-334e37be69be)

**Comment by LEDZB** [comment]
请问这个具体是如何实现的呢？或者我需要如何修改，才可以达到你这个效果呢

**Comment by LEDZB** [comment]
> 如果你问的是前一个录屏，那个是 [Wolai](https://www.wolai.com/) 的代码块，不是思源的

那请问目前针对于代码框固定高度（或者可以通过拖动，控制代码框的高度，这个有何方法呢）

**Comment by TCOTC** [comment]
比如用这个代码片段：

```css
div:not(#preview) > .protyle-wysiwyg .code-block .hljs {
    max-height: 300px;
}
```

但目前还存在问题：#12726
