### ISSUE TITLE
当代码块存在多行，行号没有变成滚轮式输出

### ISSUE THREAD

**Issue by allrobot** [siyuan-note/siyuan#11260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

不使用行号，代码块是正常的
![SiYuan_JsWJvDo3vb](https://github.com/siyuan-note/siyuan/assets/43485379/8ca625b6-f829-4788-95e3-f34b92bcb224)

使用行号后，代码块将显示所有的行号，下面留出大片的空白
![SiYuan_8NiRb4K3XJ](https://github.com/siyuan-note/siyuan/assets/43485379/966c7c70-8b1a-492c-a265-4b04c660e10b)

### Expected result

预期目标：行号和代码块一样仅显示十几行，不要全显示行号100多个

### Version environment

```markdown
- Version: latest
- Operating System: WIN10 enterprise 21H2
- Browser (if used):NO
```

### Log file

NO

**Comment by TCOTC** [comment]
这个在默认主题是没有的，请向主题/插件/代码片段作者反馈

**Comment by Achuan-2** [comment]
我之后更新下代码
把别名那些的top值调低，code block的padding-top调大
```css
.protyle-wysiwyg .code-block{
    max-height: 800px;
    overflow: auto;
    padding-top: 10px;
}
.protyle-linenumber, .protyle-linenumber__rows{
    height:100%;
}
.protyle-wysiwyg .code-block .protyle-attr {
    top: -2px;
}
```
![Clip_2024-05-06_19-10-58](https://github.com/siyuan-note/siyuan/assets/60436214/b6ff3f7b-52ca-4920-8a49-f1f5440bd65a)
