### ISSUE TITLE
怎么限制数据库换行文本的最大行数？

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11365]
https://ld246.com/article/1715443199417

### 怎么限制数据库换行文本的最大行数？

目前通过下面的代码片段可以将换行文本限制为3行：

```css
.av__row:not(.av__row--header) .av__cell[data-wrap="true"] .av__celltext {
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
  overflow: hidden;
}
```

但是鼠标悬浮在上面时无法显示全部文本：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/79a2556f-7bd5-4ab6-85a3-793da5ac9a4f)

不换行的可以显示：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/9b907bb9-81f8-4dcf-ac67-ac5790b7a906)

想知道有什么办法能让文本被截断的单元格在鼠标悬浮时显示全部文本？

---

这个代码片段还有个问题是，会导致绑定块的主键下方的那条线延长：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/44e3b6a3-fafd-48ad-baf4-019f1e90cd2c)

**Comment by Vanessa219** [comment]
这个需要修改一下 js， 下划线的话估计只能用 text-decoration: underline;

**Comment by TCOTC** [comment]
我目前选择的方案是使用下面两个代码片段：

```css
.av__row:not(.av__row--header) .av__cell[data-wrap="true"] .av__celltext {
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
  overflow: hidden;
}
```

```js
document.querySelectorAll('.av__row:not(.av__row--header) .av__cell[data-wrap="true"]:not([data-block-id])').forEach(cell => {
  const cellText = cell.querySelector('.av__celltext').textContent;
  cell.setAttribute('aria-label', cellText);
});

```

但我不知道怎么让这个 JS 在数据库 DOM 变化后重复运行，我最多只会让它隔几秒运行一次：

```js
function updateAriaLabels() {
  document.querySelectorAll('.av__row:not(.av__row--header) .av__cell[data-wrap="true"]:not([data-block-id])').forEach(cell => {
    const cellText = cell.querySelector('.av__celltext').textContent;
    cell.setAttribute('aria-label', cellText);
  });
}

// 每3秒执行一次updateAriaLabels函数
setInterval(updateAriaLabels, 3000);
```

**Comment by TCOTC** [comment]
然后我就没什么头绪了，需要 @Vanessa219 指点一下

**Comment by TCOTC** [comment]
还有个问题是主键始终会多一行

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f7c9ac5d-e955-4655-9b19-8e167d0335cf)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/72ef1b22-9911-4fc5-9c48-81ee164c33e8)

**Comment by Vanessa219** [comment]
js 要在 https://github.com/siyuan-note/siyuan/blob/50d2562a069f2ad7307941f22c8f52d0d49d3316/app/src/block/popover.ts#L26 进行修改。

多一行的问题我这里没有。

**Comment by TCOTC** [comment]
现在用这两个，只有被截断的文本才会产生悬浮提示了：

```css
/* 限制数据库换行文本最大行数 CSS片段 */
.av__row:not(.av__row--header) .av__cell[data-wrap="true"] .av__celltext {
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3; //最多3行
  overflow: hidden;
}
/* 主键下划线 */
.av__celltext--url, .av__celltext--ref {
  border-bottom: 0px;
  text-decoration: underline;
  text-decoration-color: var(--b3-border-color);
}
```

```js
/* 限制数据库换行文本最大行数 JS片段 */
document.querySelectorAll('.av__row:not(.av__row--header) .av__cell[data-wrap="true"] .av__celltext').forEach(element => {
  if (element.scrollHeight > element.clientHeight) { // 检查文本是否被截断
    const text = element.textContent.trim();  // 提取文本
    element.classList.add('ariaLabel');       // 添加 ariaLabel 类
    element.setAttribute('aria-label', text); // 添加 aria-label 属性
  }
});
```

但 JS 是一次性的，我不懂怎么让它重复运行

并且主键开启换行之后下面会多一行：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/fef97c85-8f70-4a15-b751-442488ce2d89)

**Comment by TCOTC** [comment]
这个 JS 片段不知道怎么整，只能改思源了 #11373

**Comment by TCOTC** [comment]
给文本加了 `overflow: auto;` 之后是这样的：

[空白.webm](https://github.com/siyuan-note/siyuan/assets/78434827/61169a02-fa88-4889-bed7-175bf3b25791)

**Comment by 88250** [comment]
但不能直接展开看到全部，折行的目的是为了方便看全部，不是为了截断缩减展示。

**Comment by TCOTC** [comment]
我是想在 `1 行` 和 `N 多行` 之间找个折中，只展示 1 行和全部展示是两个极端

**Comment by 88250** [comment]
这个怕是没法折中，两个需求，否则的话设计就麻烦了，还要设置一个参数给用户：保留 n 行显示

**Comment by TCOTC** [comment]
所以只用 CSS 片段就可以了

**Comment by 88250** [comment]
没有问题的话我们关闭 issue 了哦，谢谢。

**Comment by TCOTC** [comment]
还没解决呢，这个 CSS 有两个问题：

1. 截断文本没有悬浮提示
2. 主键开启换行后底下会多出一行的空间

**Comment by 88250** [comment]
@Vanessa219 有空的话再看看

**Comment by Vanessa219** [comment]
1. 稍后 js 支持
2. 贴一下完整的最终代码片段，我这里需要重现。

**Comment by TCOTC** [comment]
> 贴一下完整的最终代码片段，我这里需要重现。

如下：

```css
/* 限制数据库换行文本最大行数 CSS片段 */
.av__row:not(.av__row--header) .av__cell[data-wrap="true"] .av__celltext {
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3; //最多3行
  overflow: hidden;
}
/* 主键下划线 */
.av__celltext--url, .av__celltext--ref {
  border-bottom: 0px;
  text-decoration: underline;
  text-decoration-color: var(--b3-border-color);
}
```

![image](https://github.com/siyuan-note/siyuan/assets/78434827/fef97c85-8f70-4a15-b751-442488ce2d89)
