### ISSUE TITLE
鼠标在代码片段中选择代码，鼠标离开代码片段就反选

### ISSUE THREAD

**Issue by allrobot** [siyuan-note/siyuan#11377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

选择代码的逻辑可能有问题，选择代码时，鼠标稍微离开代码片段就反选，用户必须小心翼翼选择

### Expected result

![SiYuan_NioqMJWUH0](https://github.com/siyuan-note/siyuan/assets/43485379/17b7ece9-3804-416e-9687-2c951f89465e)

### Screenshot or screen recording presentation

预期选择代码时，不会反选，离开距离较大就全选鼠标选中点往上的全部文本
![chrome_OUVBijMLAp](https://github.com/siyuan-note/siyuan/assets/43485379/bf4a9b19-a162-4671-8520-600448b7c747)

![image](https://github.com/siyuan-note/siyuan/assets/43485379/3532fb09-1f27-42e9-843c-b0e2fddd160d)

### Version environment

```markdown
- Version: latest
- Operating System: WIN10
- Browser (if used):
```

### Log file

NO

### More information

不知道是不是归于bug，还是功能改善的

**Comment by Vanessa219** [comment]
这个是受到前面行号的影响，目前没有找到合适的解决方案。可以使用以下方式顶顶，有合适的方案再进行解决。
1. 不显示行号
2. 使用快捷键进行选择
3. 滑动的时候不要超出行号

**Comment by allrobot** [comment]
> 这个是受到前面行号的影响，目前没有找到合适的解决方案。可以使用以下方式顶顶，有合适的方案再进行解决。

当没有一个合适的解决方案时，不应该关闭Issue，因为关闭后大概率不会再打开了

**Comment by wish5115** [comment]
有个技巧，在没完成选择前不要松开鼠标左键，哪怕选择框消失，比如，拖到左侧时选择框消失，并不要紧，不要松开鼠标左键，继续拖到右侧来选择框又出现了。

**Comment by wish5115** [comment]
我用css解决了这个bug

https://ld246.com/article/1722950512427/comment/1722995482956?r=wilsons#comments

**Comment by TCOTC** [comment]
楼上的 CSS：

```css
/* 取消行号列占用的空间 */
.code-block .protyle-linenumber__rows {
    position: absolute;
    left: 0;
}
/* 当有行号时，代码块右移，给行号列让空间 */
.code-block .hljs.protyle-linenumber {
    margin-left: 3.6em;
}
```
