### ISSUE TITLE
不同文字样式导致备注区域分割&备注导致部分文字样式丢失

### ISSUE THREAD

**Issue by QMike0** [siyuan-note/siyuan#11430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

包含了两个问题：
1. 对包含不同样式的一段文字进行备注时，会导致备注被分割成多个不同的小区域，这样在撤销备注时，需要进行多次操作，查看起来也不美观
2. 备注会覆盖样式/导致部分文字样式失效，包括但不限于高亮标记、下划线、行级公式等

### Expected result

是否可以将备注作为在文字外层嵌套的另一层“容器”，从而保证不影响文字样式

### Screenshot or screen recording presentation

目前的状态如下图所示：
![recording](https://github.com/siyuan-note/siyuan/assets/43239563/059fa11a-7809-425b-831b-ee99178e8154)

### Version environment

```markdown
- Version: v3.0.14
- Operating System: Window 11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/15333424/siyuan.log)

**Comment by 88250** [comment]
感谢反馈，但是这个没有办法改了，编辑器实现多种元素是平铺的，不是嵌套的。

**Comment by QMike0** [comment]
难受555

**Comment by TCOTC** [comment]
> 备注会覆盖样式/导致部分文字样式失效，包括但不限于高亮标记、下划线、行级公式等

@QMike0 可以自己用 CSS 改一下备注的样式，比如：

```css
/* 虚线备注 CSS片段 https://github.com/TCOTC/siyuan-css-dashed-line-memo */
.b3-typography span[data-type~=inline-memo], .protyle-wysiwyg span[data-type~=inline-memo] {
    background-color: transparent;
    border-bottom: 2px dashed var(--b3-theme-primary) !important;
}
```
