### ISSUE TITLE
让悬浮面板在侧栏下方弹出与收回

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11938]
![image](https://github.com/user-attachments/assets/7386bd1f-a5e6-4f63-b7f2-771577a99096)

现在面板是从侧栏上方飘出来的，感觉很奇怪。侧栏的层级应该比悬浮面板高，让悬浮面板从侧栏下方飘出来（用侧栏挡住悬浮面板的边界）。

但目前来看，如果悬浮面板比悬浮层更高，那侧栏也要比悬浮层更高才行，更奇怪了。

所以我的解决方案是让悬浮层比悬浮面板高，改一下层级：

```css
.layout__dockl.layout--float,
.layout__dockr.layout--float {
    z-index: 4; /* 悬浮面板高于数据库 */
}
#dockLeft,
#dockRight {
    z-index: 5; /* 侧栏高于悬浮面板 */
}
```

如果有用户需要面板高于悬浮层，让用户自己用 CSS 片段改就行了，照顾其他用户的体验更重要。
