### ISSUE TITLE
Update from v3.1.0 to v3.1.1 and run with docker compose caused an error

### ISSUE THREAD

**Issue by glight2000** [siyuan-note/siyuan#12025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Update from v3.1.0 to v3.1.1 and run with `docker compose` caused an error below:
```
[+] Running 1/0
 ✔ Container siyuan-main-1  Recreated                                                                                                                                                                                         0.0s
Attaching to main-1
main-1  | E 2024/07/19 06:41:33 working.go:455: lock workspace [/siyuan/workspace/] failed: bad file descriptor
main-1 exited with code 0
```

my docker-compose.yml
```
version: "3.9"
services:
  main:
    image: b3log/siyuan:v3.1.1
    command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=123456']
    user: '1000:1000'
    ports:
      - 6806:6806
    volumes:
      - /data/siyuan:/siyuan/workspace
    restart: unless-stopped
    environment:
      # A list of time zone identifiers can be found at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=${TimeZone}
```

I'm sure this docker-compose file works well on versions before 3.1.1.

### Expected result

no errors and website works good.

### Version environment

```markdown
- Version: 
v3.1.1
- Operating System: 
Ubuntu 22.04.4 LTS Server X64
- Browser (if used):
Chrome(latest)
```

### Log file

[+] Running 1/0
 ✔ Container siyuan-main-1  Recreated                                                                                                                                                                                         0.0s
Attaching to main-1
main-1  | E 2024/07/19 06:41:33 working.go:455: lock workspace [/siyuan/workspace/] failed: bad file descriptor
main-1 exited with code 0
