### ISSUE TITLE
标签在行末时，点击行末后光标应该在标签外

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12305]
插入标签后输入、用键盘操作后输入都是正常的，唯独用鼠标点击后光标是在标签里面的，导致直接输入会变成修改标签：

[视频.webm](https://github.com/user-attachments/assets/682f4335-d44c-4ad2-b9a0-ae3061dc6294)

而用下面这个 CSS 之后就正常了：

```css
.protyle-wysiwyg span[data-type="tag"] {
    padding: 0px 1px 0px 1px;
}
```

[视频.webm](https://github.com/user-attachments/assets/cbf912aa-21e4-4c7d-b6f9-177a640219bf)

我觉得可能要默认加 padding 才行
