### ISSUE TITLE
代码块行号应该固定在左侧，只有代码可以横向滚动

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12354]
https://github.com/siyuan-note/siyuan/issues/12317#issuecomment-2314899165

---

### 01

```css
.protyle-linenumber__rows {
    position: sticky;
    left: 0;
    background-color: rgb(243,243,244);
    padding-left: 0;
    padding-right: 1em;
    min-width: auto;
    margin-right: 0;
}
```

乍一看感觉没什么问题：

![image](https://github.com/user-attachments/assets/82a863e1-ca1d-4b87-b2f7-593e071b8881)

但选中块之后就会出现跟 #12105 相同的颜色问题：

![image](https://github.com/user-attachments/assets/11d3fb5d-edf0-4f3a-b2d3-73527e872316)

### 02

```css
.code-block:not([linenumber="false"]) .protyle-linenumber__rows {
    position: absolute;
    left: 1.4em;
}
.code-block:not([linenumber="false"]) .hljs {
    margin-left: 1.8em;
}
/* 来源于 https://ld246.com/article/1724861627569 */
```

在 1000 行以前样式都正常（还能顺便解决 #11377 ）：

![image](https://github.com/user-attachments/assets/757882a1-1a03-4a49-b665-911e0c54630d)

超过 1000 行之后文本就会重叠：

![image](https://github.com/user-attachments/assets/2359d2ee-e850-48cc-b549-9e3a3f0bb387)
