### ISSUE TITLE
[v.3.1.8] 容器无法启动

### ISSUE THREAD

**Issue by redjumper** [siyuan-note/siyuan#12657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [ ] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

镜像更新到3.1.8后，无法启动
和https://github.com/siyuan-note/siyuan/pull/12596 有关，容器中已存在siyuan用户
docker logs如下
> Using existing group: siyuan (1000) 
> Creating user siyuan (PUID: 1080, PGID: 1000)
> adduser: user 'siyuan' in use
```
cat /etc/passwd
siyuan:x:1000:1000:Linux User,,,:/home/siyuan:/bin/sh)
```

### Expected result

容器中已存在siyuan用户时，不再添加siyuan用户

### Version environment

```markdown
- Version: 3.1.8
```

### Log file

docker logs如下
> Using existing group: siyuan (1000) 
> Creating user siyuan (PUID: 1080, PGID: 1000)
> adduser: user 'siyuan' in use

**Comment by 88250** [comment]
欢迎 PR 帮助改进。

**Comment by wanghan0501** [comment]
me too

**Comment by Mowen-M** [comment]
同样无法启动，PUID和PGID默认1000也不行，可能是冲突了

**Comment by redjumper** [comment]
> 欢迎 PR 帮助改进。

已提交pr #12658 
不太清楚以前的逻辑，我看v3.1.7版本的容器是以root用户运行的。pr #12596 ，如果不指定UID与PID，强制了以1000:1000运行，这是在预期内？

**Comment by 88250** [comment]
以前的版本是用 siyuan 用户运行的：

![image](https://github.com/user-attachments/assets/13d26d71-a336-48c8-9311-ce2d52f2f249)

**Comment by redjumper** [comment]
```
services:
  siyuan:
    image: b3log/siyuan:latest
    container_name: siyuan
    ports:
      - "6806:6806"
    command:
      "--lang=zh_CN --ssl=true --workspace=/siyuan/workspace/ --accessAuthCode='1234567890'"
    user: 0:0
    restart: unless-stopped
    volumes:
      - siyuan-data:/siyuan/workspace

volumes:
  siyuan-data:
```

I forgot why i add **user: 0:0**, maybe volume permissions.
