### ISSUE TITLE
使用 CSS 强制显示动态滚动条后无法向上动态加载

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12717]
页面自带的滚动条感觉很不好用，所以使用代码片段强制显示了动态滚动条：

```css
.protyle-scroll__bar {
    display: block !important;
}
```

但是无法向上动态加载：

[视频.webm](https://github.com/user-attachments/assets/7133c881-6915-4e1a-ae1d-0d0eedb95fed)
