### ISSUE TITLE
代码块行号固定在左侧

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12712]
我想到一个办法，不过无法通过纯 CSS 实现，还需要动态计算元素高度然后更新元素的内联样式（只有开启行号的代码块需要计算）：

```css
div:not(#preview) > .protyle-wysiwyg .code-block .hljs {
    max-height: 300px; /* 代码块限制高度 */
}


.code-block[linenumber="true"] .hljs > div:nth-child(2) {
    overflow-x: auto;
    height: 1000px; /* 只在.hljs有max-height属性时[Window.getComputedStyle()]需要动态计算元素高度然后更新元素的内联样式，其他情况下不需要计算，节省性能 */
}


.b3-typography .code-block[linenumber="true"] .hljs,
.protyle-wysiwyg .code-block[linenumber="true"] .hljs {
    overflow-x: hidden;
    overflow-y: auto;
}
.protyle-linenumber__rows {
    padding-right: 0.5em;
    background-color: rgb(243, 243, 244); /* 这个rgb只是临时用的，之后再改 */
}
.protyle-wysiwyg--select .protyle-linenumber__rows {
    background-color: var(--b3-av-background); /* 这个颜色基于 https://github.com/siyuan-note/siyuan/pull/12706 ，还没改好暂不用管 */
}
.protyle-wysiwyg--hl .protyle-linenumber__rows {
    transition: var(--b3-background-transition);
    background-color: var(--b3-av-background); /* 这个颜色基于 https://github.com/siyuan-note/siyuan/pull/12706 ，还没改好暂不用管 */
}
```

> #12354 的后续
