### ISSUE TITLE
建议将SIYUAN_IMAGE_FOLDER，SIYUAN_IMAGE_FILE等开放出来，用户可以自定义默认文件夹等图标

### ISSUE THREAD

**Issue by wish5115** [siyuan-note/siyuan#12721]
### In what scenarios do you need this feature?

目前思源默认的笔记本，文件夹和文件图标用户无法自定义。

建议把这三个常量开放出来用户可以自定义

[https://github.com/siyuan-note/siyuan/blob/4ef5d90af38666278473734be75c2f77da164661/app/src/constants.ts#L642](https://ld246.com/forward?goto=https%3A%2F%2Fgithub.com%2Fsiyuan-note%2Fsiyuan%2Fblob%2F4ef5d90af38666278473734be75c2f77da164661%2Fapp%2Fsrc%2Fconstants.ts%23L642)

类似这种配置效果

![组合 5](https://github.com/user-attachments/assets/9d52b1fe-8194-4ee9-ba27-edf0de5da4bf)

关联帖子 https://ld246.com/article/1728246523163

### Describe the optimal solution

笔记本，文件夹和文件默认图标用户可以自定义。

**Comment by TCOTC** [comment]
需要不增加菜单选项的方案

**Comment by wish5115** [comment]
> 需要不增加菜单选项的方案

具体怎么加？你可以说说你的想法。

**Comment by TCOTC** [comment]
等我晚上想想

**Comment by TCOTC** [comment]
1. 实时更新文档树上文档的 data-count 属性
2. 添加一个 `data-customicon` 属性用于表示文档是否有自定义图标
3. 把鼠标悬浮在图标上显示的伪元素提示换成悬浮提示

然后再使用以下 CSS 片段：

```css
/* 笔记本 */
.layout-tab-container > .file-tree > .fn__flex-1 > ul.b3-list[data-url] > li.b3-list-item[data-type="navigation-root"] > .b3-list-item__icon {
    color: transparent;
}
.layout-tab-container > .file-tree > .fn__flex-1 > ul.b3-list[data-url] > li.b3-list-item[data-type="navigation-root"] > .b3-list-item__icon::before {
    color: black;
    content: "🗃"; /* 笔记本图标自定义 */
    position: absolute;
}

/* 文档 */
.layout-tab-container > .file-tree > .fn__flex-1 li.b3-list-item[data-node-id]:not([data-count="0"]):not([data-customicon="1"]) > .b3-list-item__icon {
    color: transparent;
}
.layout-tab-container > .file-tree > .fn__flex-1 li.b3-list-item[data-node-id]:not([data-count="0"]):not([data-customicon="1"]) > .b3-list-item__icon::before {
    color: black;
    content: "📑"; /* 文档图标自定义 */
    position: absolute;
}
```
