### ISSUE TITLE
代码块尾部的空行无法显示

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12726]
用了自定义css片段折叠代码块后存在一些问题：

```css
div:not(#preview) > .protyle-wysiwyg .code-block .hljs {
    max-height: 300px;
}

```
**问题**
1. 在不开启行号的情况下，经过一定行后（大概就是设置的代码最大高度），直接在末尾按enter，不会创建新行，只有先打几个字，在中间按enter才能创建新行
2. 在开启行号的情况下，按enter一直能创建新行，但可视区域不会自动移到下一行，需要手动滚动

[视频.webm](https://github.com/user-attachments/assets/320a74b3-2b6c-4706-8cd8-32275a1473c0)

**希望**：
不开启行号的情况下，直接在末尾按enter，能创建新行，并且可视区域能自动移动到新创建的代码块行

备注：已经在新工作空间测试

_Originally posted by @Achuan-2 in https://github.com/siyuan-note/siyuan/issues/10769#issuecomment-2395672916_
