### ISSUE TITLE
使用docker-compose 提示addgroup: permission denied (are you root?) 

### ISSUE THREAD

**Issue by helingjun** [siyuan-note/siyuan#12871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用docker-compose 提示addgroup: permission denied (are you root?) 

### Expected result

以前的版本能够正常运行

### Screenshot or screen recording presentation

<img width="855" alt="image" src="https://github.com/user-attachments/assets/c184af37-f1b8-468c-bc34-8026288da8e6">

docker-compose.yaml 内容如下

```
services:
  siyuan:
    image: b3log/siyuan:latest
    container_name: siyuan
    environment:
      - TZ=Asia/Shanghai
    user: '1000'
    privileged: true
    restart: always
   ports:
      - 6806:6806
    volumes:
      - ./workspace/:/siyuan/workspace
    command:
      - --accessAuthCode=xxxx

```

### Version environment

```markdown
- Version: latest
- Operating System:  docker-compose
- Browser (if used):
```

### Log file

无法启动
