### ISSUE TITLE
界面降噪：减少使用边框

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12970]
用颜色区分界面和编辑器即可，使用边框会看起来会有一点杂乱：

![image](https://github.com/user-attachments/assets/bdef502c-583d-4103-916f-5452651fea3f)

隐藏边框后看起来更干净，更融合，用户可以更专注于功能，不需要关心顶栏/侧栏/底栏的边界：

```css
.toolbar,.dock,.status {
	border-left:none !important;
	border-right:none !important;
	border-top:none !important;
	border-bottom:none !important;
}
```

![image](https://github.com/user-attachments/assets/4fdab0fd-94c9-4934-b9cc-af04a784534b)

---

比如 Craft 这种样式，编辑器还带一点点圆角：

![image](https://github.com/user-attachments/assets/a4bf005b-b00c-4184-a85d-be46b0828f88)
