### ISSUE TITLE
划选的过程中不应该频繁添加和移除选中块的 `protyle-wysiwyg--select` 类名

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13028]
我感觉是 DOM 更新影响了 transition 样式（看起来一直在闪）：

```css
.protyle-wysiwyg--select {
    transition: var(--b3-background-transition);
}
```

[video.webm](https://github.com/user-attachments/assets/84759258-de3b-48d0-9a96-c713042fe478)

**Comment by Vanessa219** [comment]
现在应该没有这个问题了，我先关闭了。

**Comment by TCOTC** [comment]
我这里还是像录屏这样的

**Comment by Vanessa219** [comment]
现在已经没有 transition 了，强制刷新看看

**Comment by TCOTC** [comment]
还是会影响的，比如这个：

```css
.protyle-wysiwyg--select:after, .protyle-wysiwyg--hl:after {
    animation-duration: 0.3s; /* 动画持续时间 */
    animation-fill-mode: forwards; /* 保持最终状态 */
    animation-name: fade-in; /* 使用淡入动画 */
}

/* 定义关键帧动画 */
@keyframes fade-in {
    0% {
        opacity: 0; /* 开始时透明 */
    }
    100% {
        opacity: 1; /* 结束时完全可见 */
    }
}
```

[video.webm](https://github.com/user-attachments/assets/05cfe6f0-41d9-43cc-9376-0b291ea2e192)
