### ISSUE TITLE
解决嵌套和有颜色的块下数据库和表格颜色问题

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#13052]
https://github.com/siyuan-note/siyuan/issues/12713
https://github.com/siyuan-note/siyuan/issues/12951
![QQ_1730864850344](https://github.com/user-attachments/assets/a3e88f6d-1047-48b9-9798-afbe039846f9)

**Comment by TCOTC** [comment]
嵌入块那个左侧虚线框看起来怪怪的，

我建议把

```css
.protyle-wysiwyg [data-node-id].render-node[data-type=NodeBlockQueryEmbed] {
    border-left: 1px dashed var(--b3-theme-surface-lighter);
}
```

换成

```css
.protyle-wysiwyg [data-node-id].render-node[data-type=NodeBlockQueryEmbed] {
    border: 1px dashed var(--b3-theme-surface-lighter);
}
```
