### ISSUE TITLE
span元素white-space和word-wrap样式换行识别

### ISSUE THREAD

**Issue by ruin1990** [siyuan-note/siyuan#13195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

最近使用中发现许多文章如果段落中换行基本是没有，然后只使用了span进行一行行文字的拆分，本来默认span是不会换行的
但是呢，如果span被设置了如下样式,则应当被视为一个换行：
```css
        .wrap {
            white-space: normal; /* 或者使用 pre-wrap */
            word-wrap: break-word; /* 确保长单词也能被拆分换行 */
        }
```
测试用例：https://www.bilibili.com/opus/465490977904921957

发现文本每一行都是span，段落之间是p标签分开
![image](https://github.com/user-attachments/assets/d64422fc-67ec-4581-8971-6cc4b6fdf417)
可以看到使用了上述的样式：
![image](https://github.com/user-attachments/assets/a4b40ab4-4575-4551-aa80-3b7919e49c2d)

### Expected result

![image](https://github.com/user-attachments/assets/6023b8ed-34e3-420f-8fa1-7eda0d40a0f7)

### Version environment

```markdown
- Version: 3.1.11
- Operating System: Win10 14939
- Browser (if used): Thromium 126
```

### Log file

实际文本摘录的时候span文字段沾到了一起，是否能判断下`white-space: normal; /* 或者使用 pre-wrap */`和 `word-wrap: break-word; /* 确保长单词也能被拆分换行 */`的span元素，末尾自动加个换行
