### ISSUE TITLE
导出pdf时，如果代码块被分页，代码块会被延长，影响后面元素

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#13349]
### In what scenarios do you need this feature?

![PixPin_2024-12-03_12-37-34](https://github.com/user-attachments/assets/6ece5a0e-f529-4f45-9f00-741ab23b0425)

代码块导出pdf，会发现如果代码块正好在两页中间，代码块的背景就会比原来的更长一些，就会影响到后面的元素，请问该如何解决

测试文档

[代码块导出pdf效果.sy.zip](https://github.com/user-attachments/files/17987442/pdf.sy.zip)

### Describe the optimal solution

希望能解决这个问题，不然很影响导出pdf的效果

### Describe the candidate solution

无

**Comment by Achuan-2** [comment]
发现不能给code-block添加padding，得给hljs加
```css
#preview .protyle-wysiwyg .code-block {
    width: 98% !important;
    margin: 0em auto;
    padding: 0px;
}

#preview .protyle-wysiwyg .hljs {
    padding: 2em 1em 0.6em;
}
```
