### ISSUE TITLE
侧栏展开时会有滚动条

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13469]
![image](https://github.com/user-attachments/assets/b69d0d96-9f42-41e4-ad44-c9b95b9153d7)

用这个代码片段之后就能隐藏滚动条了：

```css
.fn__flex-column, .fn__flex-1 {
    overflow-x: hidden;
}
```

[video.webm](https://github.com/user-attachments/assets/6061dcdc-7308-4c15-8737-91e4cf63f091)

**Comment by Vanessa219** [comment]
好像不能这样改，这些类里面是需要现滚动条的。

试了下其他方案都不太理想，先这样吧。

**Comment by TCOTC** [comment]
这个怎样：

```css
.file-tree, .file-tree > .fn__flex-1 {
    overflow-x: hidden;
}
```

**Comment by Vanessa219** [comment]
内部也会有滚动条的情况

![image](https://github.com/user-attachments/assets/46a24f7e-6c59-48e4-a801-6021be939762)

**Comment by TCOTC** [comment]
这是怎么弄出来的？

**Comment by Vanessa219** [comment]
你可以把顶部文案改为长一点的语言

**Comment by TCOTC** [comment]
@Vanessa219 我这里没重现这个滚动条，是哪个元素上的？

另外再更新一下上面的 CSS，把 layout 的横向滚动条解决一下：

```css
:is(.layout, .file-tree),
:is(.layout, .file-tree) > .fn__flex-1 {
    overflow-x: hidden;
}
```

![Image](https://github.com/user-attachments/assets/f478b099-db88-4066-8566-21d53ecaedbc)
