### ISSUE TITLE
使用 `href` 替换 `xlink:href`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13513]
尝试 https://ld246.com/article/1734427196426 的时候发现选择器选不到 [xlink:href="#iconListItem"] 的元素，然后查到 xlink:href 已弃用：https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

**Comment by wish5115** [comment]
这一替换估计会倒下一片插件或js代码😁。

**Comment by TCOTC** [comment]
有什么插件会需要用这个吗？

**Comment by cordinGH** [comment]
![Screenshot_2024-12-18-02-32-44-902_com.android.browser-edit.jpg](https://github.com/user-attachments/assets/1461c558-5801-44c3-bdff-b64808c86f78)

也可以和mdn提到的那样，两个一起写。

**Comment by wish5115** [comment]
> 主题和代码片段应该不影响，选择器选不中。有什么插件会需要用这个吗？

不知道，猜的，应该有一小部分用到吧，一般不多，我记得你有个js代码片段就有用到这个，我也用过这个做一些判断。

**Comment by TCOTC** [comment]
用这个可以了，那就不动了：https://ld246.com/article/1734427196426/comment/1734486397365#comments

```css
@namespace xlink 'http://www.w3.org/1999/xlink';

.protyle-breadcrumb__item:has(use[xlink|href*=iconListItem]) .protyle-breadcrumb__text {
    display: none;
}
```
