### ISSUE TITLE
某种情况下会导致侧栏面板宽度很小并且无法调整宽度

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13516]
## 01

新建工作空间使用如下 CSS 片段：

```css
.layout__dockr > .fn__flex-1 {
	margin-left: 3px;
}
```

会这样：

[video.webm](https://github.com/user-attachments/assets/b043daea-f114-4216-95c9-1449b8e62f83)

## 02

本来想用 :not(.fn__none) 规避：

```css
.layout__dockr > .fn__flex-1:not(.fn__none) {
	margin-left: 3px;
}
```

但是发现界面加载之后元素默认没有添加 .fn__none，只有展开侧栏再收起才会加上。这部分逻辑也需要修改一下：

[video.webm](https://github.com/user-attachments/assets/03188331-a1ae-431c-a632-6f2d5535f250)

**Comment by TCOTC** [comment]
给侧栏面板加个最小宽度限制应该能解决问题：

```css
.layout__dockl, .layout__dockr {
    min-width: 232px;
}
```
