### ISSUE TITLE
请问在文档树中浏览较长的子文档列表时，能否将父层级sticky到文档树顶部？

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#13517]
### In what scenarios do you need this feature?

（emmm，想了想用css的sticky作为描述最明确。）

提出这个功能需求主要是两个原因，一个是子文档列表过长，有时候比较难以注意到当前聚焦文档在哪一个层级下，第二个原因是在这一情况下，折叠和定位父文档稍微有些困难。

### Describe the optimal solution

在文档树中浏览较长的子文档列表且父文档被滚动到视口之外时，将父层级暂时sticky到文档树顶部。

大概就是下图这个意思。

![image](https://github.com/user-attachments/assets/c7805c78-b2fe-4af2-b06c-d508f92aaee8)

**Comment by TCOTC** [comment]
大概可以像这样写，但是用起来会很奇怪：

```css
.b3-list .b3-list-item {
    position: sticky;
    top: 0;
    background-color: var(--b3-theme-surface);
    z-index: 1;
}
.b3-list .b3-list-item:hover {
    background-color: var(--b3-theme-surface) !important;
}
.b3-list >ul> .b3-list-item {
    top: 29px;
    z-index: 1;
}
.b3-list >ul>ul> .b3-list-item {
    top: 58px;
    z-index: 1;
}
……
```
