### ISSUE TITLE
CSS 默认给悬浮提示和伪元素提示加个显示延迟

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13642]
https://news.ycombinator.com/item?id=42512713#42517399

![image](https://github.com/user-attachments/assets/d4e0fc4c-2cc5-48df-b0fd-b4c82f876a31)

**Comment by Vanessa219** [comment]
延迟也会弹出，依然会 noisy

**Comment by Jiangshuon** [comment]
我感觉现在这样更好

**Comment by 88250** [comment]
需要有一定延时弹出更好一些，不然鼠标在文档树上移动的时候视觉干扰太强了。

**Comment by TCOTC** [comment]
比如我的主题就是延迟弹出的，用了 `animation-delay`

```css
@keyframes tooltipFadeIn {
    from {
        opacity: 0;
    }
    to {
        opacity: 1;
    }
}
.tooltip {
    animation-name: tooltipFadeIn;
    animation-duration: 100ms; // 过渡时间
    animation-delay: 800ms;    // 延迟显示
}
```
