### ISSUE TITLE
Please enteImprove database visualization when there is a one-to-many (1:N) relationship

### ISSUE THREAD

**Issue by Wil24555** [siyuan-note/siyuan#13692]
### In what scenarios do you need this feature?

The aim is to improve the visualization of the database when the relationship is one to many. I would like the visualization to be the same as the multi-select attribute selection system, including the same color system.

In the current view, it is a little confusing to see that an author is related to two books, when only viewing the author database, as per the example.
![Visão atual](https://github.com/user-attachments/assets/eab09029-180c-440d-b19e-ab41ea114cd5)

### Describe the optimal solution

![Relação um para muitos](https://github.com/user-attachments/assets/c69fdad4-41dd-4117-a3b3-0545c29dda8b)

**Comment by TCOTC** [comment]
@Vanessa219 我觉得可以用这个样式：

```css
.av__cell:not(.av__cell--header)[data-dtype="relation"] .av__celltext:hover {
    border-bottom: 2px solid var(--b3-border-color);
}
.av__cell:not(.av__cell--header)[data-dtype="relation"] .av__celltext:not(:last-of-type)::after {
    content: ",";
}
```
