### ISSUE TITLE
Settings - Editor - Font is garbled on macOS

### ISSUE THREAD

**Issue by tinywaves** [siyuan-note/siyuan#13713]
文档的标题中文渲染似乎有问题

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

中文标题似乎在渲染上有问题，正文也有这个问题，有点像编码问题
![CleanShot_2025-01-03_16 02 23@2x](https://github.com/user-attachments/assets/b6c9e0b2-acd4-4747-8a24-bd3ac4905c31)
![CleanShot_2025-01-03_16 04 13@2x](https://github.com/user-attachments/assets/9adc5b05-6d16-4cbe-9ade-f3143176a966)
我发现在选择字体的时候，选项全都乱码了，这个该咋解决
![CleanShot_2025-01-03_16 04 47@2x](https://github.com/user-attachments/assets/55abeb62-f167-45da-81d9-c2e5d7c17f84)

### Expected result

/

### Version environment

```markdown
- Version: Version 3.1.18 (3.1.18)
- Operating System: macOS 15.2
- Browser (if used):
```

### Log file

/

**Comment by 88250** [comment]
标题的字体问题： https://github.com/siyuan-note/siyuan/pull/13688

设置字体列表乱码稍后排查。

**Comment by TCOTC** [comment]
我那个PR应该只影响Windows，Mac上的字体问题我不清楚

@tinywaves 麻烦像这样操作看看标题渲染的字体是什么：


https://github.com/user-attachments/assets/d133f0fe-6bb5-49dd-8165-5799aa767a6b

**Comment by tinywaves** [comment]
> 我那个PR应该只影响Windows，Mac上的字体问题我不清楚
> 
> @tinywaves 麻烦像这样操作看看标题渲染的字体是什么：
> 
>  video-uMuCWtO.mp4

![CleanShot_2025-01-03_17 24 45@2x](https://github.com/user-attachments/assets/bcff98aa-23fa-4ffb-ad7e-7406a26056b4)
是一个很奇怪的字体

**Comment by TCOTC** [comment]
麻烦用下面这个 CSS 代码片段测试一下，从 `BlinkMacSystemFont,` `Helvetica,` ... 开始，每次删一个，看看删掉哪个字体之后能正常显示

```css
:root:lang(zh_CN) {
    --emoji-font-family: "Emojis Additional", "Emojis Reset";
    --b3-font-family: var(--emoji-font-family), BlinkMacSystemFont, Helvetica, "PingFang SC", "Luxi Sans", "DejaVu Sans", arial, "Microsoft Yahei", "Hiragino Sans GB", "Source Han Sans SC", sans-serif, emojis;
}
```
