### ISSUE TITLE
动态加载时 .protyle-content 禁止滚动，但文档中的 iframe 块还在滚动

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13913]
## 01

动态加载时 .protyle-content 被加上 width 会影响布局发生抖动
会突然变窄一点：

https://github.com/user-attachments/assets/43604c84-95c9-4d9a-905c-2f333f0f1033

原因是 .protyle-content 在一瞬间被加上了 width 又去除：

![Image](https://github.com/user-attachments/assets/14b816b4-1a0d-484e-8929-131c1b418e55)

我在代码片段里加了 `.protyle-content{width:unset!important;}` 之后就不会发生抖动了

---

更新：

发现这个问题在添加了以下样式后出现：

```css
.protyle-content {
    scrollbar-gutter: stable;
}
```

抖动是因为 .clientWidth 没有考虑滚动条占的宽度，换成 .offsetWidth 就能解决了。
