### ISSUE TITLE
光标在表格内时，表格不应该有外边框样式

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13973]
![Image](https://github.com/user-attachments/assets/e2216193-ad7e-4247-b7fe-f34e25aec9fc)

用户代理样式表：

![Image](https://github.com/user-attachments/assets/4a861c08-52c6-4eb8-a2ab-bb5d08b16585)

用这个 CSS 能解决：

```css
:focus-visible {
    outline: unset;
}
```
