### ISSUE TITLE
Block scrollbar style is incorrect

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#14085]
修复动态滚动条样式

> [如果在选择器的链或组中有一个无效的伪类，那么整个选择器列表都是无效的。](https://developer.mozilla.org/zh-CN/docs/Web/CSS/WebKit_Extensions#%E4%BC%AA%E7%B1%BB)

https://github.com/siyuan-note/siyuan/commit/df0c1fa93efdd9351775db102c7ac591ce313cdc 的修改把样式改坏了：

![Image](https://github.com/user-attachments/assets/dc2e27df-43cc-4da8-a20c-c1fb54985083)

![Image](https://github.com/user-attachments/assets/b71a645a-1dfa-4dbe-a93e-46b64e05b6ff)

AI 说可以像这样改：

```scss
@mixin slider-thumb-style {
    -webkit-appearance: none;
    width: 10px;
    height: 10px;
    border-radius: var(--b3-border-radius-b);
    cursor: pointer;
    background-color: var(--b3-theme-primary);
    margin-top: -4px;
    box-shadow: var(--b3-point-shadow);
    transition: transform 100ms ease-out;
}

.b3-slider::-moz-range-thumb {
    @include slider-thumb-style;
}

.b3-slider::-webkit-slider-thumb {
    @include slider-thumb-style;
}
```
