### ISSUE TITLE
数据库主键图标会有一瞬间被添加 `data-unicode="undefined"` 属性

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#14121]
正常情况应该是 data-unicode 属性没有值。

https://github.com/user-attachments/assets/a1ce8895-e5b9-475b-8f63-950e0e8b8236

```css
.b3-menu__avemoji[data-unicode="undefined"] {
	background-color: black;
}
```
