### ISSUE TITLE
Improve display reference counts in embed blocks

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#14129]
嵌入的对应内容块，如果块引计数 < 2，就不必在嵌入块中显示

嵌入块无论如何都有块引计数，感觉不太简洁。打开反链浮窗，指向的又是这个嵌入块本身，是冗余的。故我认为应该隐藏这种块引计数。

https://github.com/user-attachments/assets/09b9b159-d215-45e7-99be-0e1d458de448

**Comment by 88250** [comment]
继续改进 https://github.com/siyuan-note/siyuan/issues/13678

**Comment by Hzz-0802** [comment]
我感觉，大于 1 才显示，就可以了吧。

**Comment by TCOTC** [comment]
小于2不显示 不就等价于 大于1显示

**Comment by TCOTC** [comment]
@88250 我这里看没有变化，是改了哪里？

![Image](https://github.com/user-attachments/assets/2fa9ebb8-74d6-40b7-a3ad-511bf8edff5d)

**Comment by 88250** [comment]
我这里测试正常：

![Image](https://github.com/user-attachments/assets/f936bca7-a428-4408-9da9-52c1812703f8)

你看下是不是没有编译内核，改动点 d4349ea6d69beb1e41adba9160137f8c9e900027

**Comment by TCOTC** [comment]
### 01

这样能复现：

https://github.com/user-attachments/assets/db25fd52-c156-44a1-a5ea-79cc2826ae77

### 02

应该是隐藏被嵌入的顶层块的块引计数（作用是避免出现指向这个嵌入块本身的反链浮窗），现在会把其他块的计数也隐藏：

https://github.com/user-attachments/assets/e78430dd-d222-45db-9e37-f263d0602fbd

**Comment by 88250** [comment]
再尝试改了一下，搞不定，这个问题较为复杂，还是回滚保持原样吧。

**Comment by TCOTC** [comment]
我想到了一段 CSS 几乎能解决问题，分享一下：

```css
/* 不显示指向嵌入块自身的块引计数 `1` CSS片段 */
[data-type="NodeBlockQueryEmbed"][data-content*="select * from blocks where id='"] > .protyle-wysiwyg__embed:nth-child(2) > [data-node-id][refcount="1"] > .protyle-attr > .protyle-attr--refcount {
    display: none;
}
.protyle-wysiwyg__embed:has(+.protyle-wysiwyg__embed) > [data-node-id][refcount="1"] > .protyle-attr > .protyle-attr--refcount {
    display: block !important;
}
```
