### ISSUE TITLE
S3 api error SignatureDoesNotMatch

### ISSUE THREAD

**Issue by JannikWilhelm** [siyuan-note/siyuan#14223]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [x] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [x] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I am trying to set up cloud sync using a minio S3 connection behind cloudflare proxy.
Connecting from the local network to the minio server, everything works fine and syncs correctly.
However, when updating the endpoint from http://[local IP adress]:9000 to https://s3.mydomain.tld, this error is generated (by clicking on Cloud Sync directory)

`operation error S3: ListBuckets, https response error StatusCode: 403, RequestID: 1828010AA525A8FF, HostID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Provider: S3)`

I can connect using mc (minio client) on the external url and have disabled cloudflare caching and "add security headers" already

according to https://github.com/minio/minio/issues/15693#issuecomment-1255413538 updating the s3 sdk possibly could solve the problem

possibly related to https://github.com/siyuan-note/siyuan/issues/13805?

### Expected result

syncronization should work like when using local IP adress

### Screenshot or screen recording presentation

![Image](https://github.com/user-attachments/assets/4bd91172-b33c-4120-9789-11495feb3751)

![Image](https://github.com/user-attachments/assets/2ebff43b-1e0a-4f81-abfd-28ede590dbc9)

### Version environment

```markdown
- Version: 3.1.23
- Operating System: Linux Fedora 41
- Browser (if used): Firefox 135.0.1 (64-Bit), Flatpak-Application (https://flathub.org/apps/org.b3log.siyuan), AppImage from latest release
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/19005198/siyuan.log)

**Comment by 88250** [comment]
Please refer to https://github.com/minio/minio/issues/15506

**Comment by JannikWilhelm** [comment]
I managed to solve the issue, by setting up a small nginx-instance in the docker network for minio, which just sets the correct header.
For everyone with the same Problem:

docker-compose.yml:
```yml
version: '3.8'

services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: $ROOT_PWD
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=$CF_TUNNEL_TOKEN
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
```

nginx.conf:
```cfg
events {
  worker_connections 1024;
}

http {
  server {
    listen 80;
    server_name s3.mydomain.tld;
    location / {
      proxy_set_header Host $host; #keep host the same
      proxy_set_header Accept-Encoding "identity";#set correct header
      proxy_pass http://minio:9000;#pass on to minio s3
    }
  }
}
```

In Cloudflare: Disable caching, point the Tunnel to `http://proxy:80`
