### ISSUE TITLE
闪卡窗口的背景太亮了

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#14320]
![Image](https://github.com/user-attachments/assets/c36a2e40-2f6a-4838-ba14-7595433da173)

我觉得跟其他窗口一样用 --b3-mask-background，大概是这样的效果：

```css
.b3-dialog--open[data-key="dialog-opencard"] .b3-dialog__scrim::before {
	content: '';
	display: block;
	position: fixed;
	width: 100%;
	height: 100%;
	top: 0;
	left: 0;
	background-color: var(--b3-mask-background);
}
```

https://github.com/user-attachments/assets/6c75ec57-9ed0-45df-bc67-2729078868cf
