### ISSUE TITLE
希望改进列表的排版（间距）

### ISSUE THREAD

**Issue by ihnfsax** [siyuan-note/siyuan#14478]
### In what scenarios do you need this feature?

思源默认主题下，相比于 Github 的 Markdown 格式，无序/有序列表的排版有两个不一样的点：

1. 相比 Github，思源列表的左侧数字/黑点距离文字间距太大。
2. Github 上，列表每一项的间距比段间距小，而思源是一样。

对比如下：

![img](https://s3.bmp.ovh/imgs/2025/03/30/7e226d820723b847.png)

关于第二点，Github Markdown 的列表在两种不同情况下的间距是不一样的：

和段间距一样：

- 第1项。

- 第2项。

- 第3项。

```markdown
- 第1项。

- 第2项。

- 第3项。
```

比段间距小：

- 第1项。
- 第2项。
- 第3项。

```markdown
- 第1项。
- 第2项。
- 第3项。
```

### Describe the optimal solution

个人认为能直接提供 Github 主题就再好不过了，给用户多一个选择。

**Comment by TCOTC** [comment]
这个得自己用 CSS 改了，不过不太推荐改，很麻烦

**Comment by ihnfsax** [comment]
> 这个得自己用 CSS 改了，不过不太推荐改，很麻烦

@TCOTC 就是怕改出问题，希望能有原生支持

**Comment by Vanessa219** [comment]
涉及到拖拽、高亮、背景等因素，列表内部是列表项，列表项内是块元素，因此是需要一定间距以区分的。

![Image](https://github.com/user-attachments/assets/09f8b62c-eade-403d-917b-0aa5c5417a8d)

https://github.com/siyuan-note/siyuan/issues/13201
https://github.com/siyuan-note/siyuan/pull/13564

**Comment by ihnfsax** [comment]
可惜了，这个对我来说还挺重要的。

我自己改了一个，有块间距，效果还行，只是 .protyle-gutters button 没法对齐，改 css 没有用。

![img](https://s3.bmp.ovh/imgs/2025/03/31/5e3c51884e4e83c8.png)

```css
.protyle-wysiwyg [data-node-id].li>.protyle-action {
    height: 26px;
}

.protyle-wysiwyg [data-node-id].li>[data-node-id] {
    padding-top: 0;
    padding-bottom: 0;
    margin-left: 26px;
}

.protyle-wysiwyg [data-node-id].list>div:nth-last-child(2) {
    min-height: 26px;
}

.protyle-wysiwyg [data-node-id].li>.protyle-action svg {
    width: 26px;
}

.protyle-wysiwyg [data-node-id].li>.protyle-action {
    width: 26px;
}

.protyle-wysiwyg [data-node-id].li::before {
    left: 13px;
    top: 34px !important;
    height: calc(100% - 34px) !important;
}

.protyle-wysiwyg [data-node-id].list {
    padding: 2px;
}

.protyle-wysiwyg [data-node-id].li {
    min-height: 26px;
}
```

**Comment by Vanessa219** [comment]
调整一下这个试试
```css
.protyle-gutters button svg {
    height: 18px;
}
```

**Comment by ihnfsax** [comment]
> 调整一下这个试试
> 
> .protyle-gutters button svg {
>     height: 18px;
> }

试了没有用。不是高度问题，是 paddding，下面的 css 能将左侧按钮与调整后的列表上下居中对齐，但是会导致普通段落左侧的按钮上移，我还没找到一个只限定列表左侧按钮的选择器：

```css
.protyle-gutters button {
    padding-top: 0;
    padding-bottom: 0;
}
```
