### ISSUE TITLE
Syncing large Files via Cloudflare Tunnel not working

### ISSUE THREAD

**Issue by JannikWilhelm** [siyuan-note/siyuan#14487]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [x] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [x] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

When syncing using S3 with minio, everything works as expected, except for syncing larger assets (>3MB).
If suhc assets are in the Workspace, sync only works using a direct connection to the S3 backend, but not via the Cloudflare Tunnel. Error notification: `Sync failed: The network is abnormal, please try again later (Provider: S3) v3.1.26`

### Expected result

Even when syncing larger files with a Cloudflare Tunnel, the files should be synced.

### Screenshot or screen recording presentation

https://github.com/user-attachments/assets/a5a596df-02d9-4de3-b4a6-b11c8f8644fa

The added File is a libreoffice ODP-Presentation, 3.4MB in size

### Version environment

```markdown
- Version: 3.1.26
- Operating System: Fedora Linux
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/19537592/siyuan.log)

### More information

[minio-largefile-.zip](https://github.com/user-attachments/files/19537585/minio-largefile-.zip) contains two wireshark captures:
- minio-largefile-localnet.pcapng: working sync via the local network
- minio-largefile-remotenet.pcapng: non-working sync via the Cloudflare Tunnel

No packages seem to be rejected, but in the remote capture, the indexes and refs do not get updated. It just stops after a few put operations and deletes the lock-sync file.

minio docker-compose.yml
```
version: '3.8'

services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: $ROOT_PASSWORD
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - 80:80
      #- 443:443
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf

```

nginx configuration to restore correct headers (see #14223): 
```
# nginx.conf
events {
  worker_connections 1024;
}

http {
  server {
    listen 80;
    server_name s3.jannikwilhelm.de;
    location / {
      proxy_set_header Host $host;
      proxy_set_header Accept-Encoding "identity";
      proxy_pass http://minio:9000;
    }
  }
}

```
The cloudflare Tunnel points to `proxy:80` as exit point
