### ISSUE TITLE
多选块右上角会选中零宽空格

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#14614]
### In what scenarios do you need this feature?

之前的 issue 找不到了。

我想到一个方案，使用以下 CSS：

```css
.protyle-attr::selection {
  background: transparent;
}
.protyle-attr > div::selection {
    background-color: var(--b3-theme-primary-lighter);
}
```

### Describe the optimal solution

。

**Comment by TCOTC** [comment]
另外我觉得还是有必要再问一个问题：这里的零宽空格真的不能去掉吗？

![Image](https://github.com/user-attachments/assets/d6129a39-4a57-4eb4-8a5e-44ffd697dfb8)

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/commit/f7a69e20650e2df9538c572030c2e6325fc9e555 修改后又试了一下，角标上的文本在多选块时不会显示被选中了，但零宽空格还是会出现这个情况。所以添加以下 CSS 即可：

```css
.protyle-attr::selection {
    background: transparent; /* 角标上的零宽空格 */
}
```
