### ISSUE TITLE
强烈请求加上自定义icon颜色

### ISSUE THREAD

**Issue by CG1995** [siyuan-note/siyuan#14633]
### 比如我喜欢类似notion或者obsidian的扁平化icon而不是emoji，我觉得我应该不是孤例，但是很可惜无法自定义颜色（如图所示），其实我只希望在暗色主题下显示为白色，亮色主题下显示为灰色就行。

![Image](https://github.com/user-attachments/assets/efa73d74-3373-46db-8da5-f73963caf2d2)

### Describe the optimal solution

---

**Comment by TCOTC** [comment]
麻烦发其中一个图标文件让我测试一下

**Comment by CG1995** [comment]
@TCOTC [参考这个](https://raw.githubusercontent.com/simple-icons/simple-icons/refs/heads/develop/icons/2fas.svg)

**Comment by TCOTC** [comment]
试试这个 CSS 代码片段是不是你想要的效果：

添加到 设置 - 外观 - 代码片段 中（并开启两个开关）

```css
html[data-theme-mode="dark"] img[src$=".svg"] {
    filter: brightness(0) invert(1);
}
```
