### ISSUE TITLE
代码块主题的 `.hljs ::selection, .hljs::selection` 会覆盖 `.protyle-wysiwyg--hiderange ::selection`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#14644]
需要再加一段 CSS：

```css
.protyle-wysiwyg--hiderange .hljs ::selection {
    background-color: transparent;
    color: inherit;
}
```

![Image](https://github.com/user-attachments/assets/8b1add6d-3434-4f80-a103-c1ccba7eb590)

---

关联 https://github.com/siyuan-note/siyuan/pull/14010
