### ISSUE TITLE
划选到块的 margin 范围中时无法选中块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#14663]
目前鼠标划选到其他块上的时候不会立即选中块

期望的效果是鼠标移入块的时候立即添加 protyle-wysiwyg--select 类名，不会出现跨块选中文本的情况：

- [ ] 从上往下划 https://github.com/siyuan-note/siyuan/pull/14996
- [ ] 从下往上划

![Image](https://github.com/user-attachments/assets/c446b0f0-9ca9-4db1-86c5-9987411100d2)

对比思源、wolai、FlowUs 作为参考：

https://github.com/user-attachments/assets/a5a0d20c-e774-4b57-b495-7415f7e8aa6a

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/15331

**Comment by Vanessa219** [comment]
3.7.0

**Comment by TCOTC** [comment]
```css
.protyle-wysiwyg [data-node-id] {
    margin-top: 40px !important;
    margin-bottom: 40px !important;
}
```

好像没啥区别：

https://github.com/user-attachments/assets/37d39ec9-38e2-41dc-ba66-25e64ea80d1f
