### ISSUE TITLE
改进特殊字符字形

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#14697]
### 问题

比如 `↕` (2195) 和 `↕️` (2195-fe0f) 是不同的字符，但思源里都会显示为后面的 emoji 字形

1. https://github.com/siyuan-note/siyuan/pull/13241#issuecomment-2552121534

   ![Image](https://github.com/user-attachments/assets/522ef97a-1035-4aef-869e-f29d3a4bf789)

2. 三群

   ![Image](https://github.com/user-attachments/assets/5e97d3de-84b2-480f-a5e5-ab8ae5c8308f)

### 方案

可能需要再加一个 font-face，参考：

```css
/* 普通箭头 ↕ (U+2195) 使用 Arial */
@font-face {
  font-family: "NormalArrow";
  src: local("Arial");
  unicode-range: U+2195;
}

/* 表情箭头 ↕️ (U+2195 + U+FE0F) 使用 Segoe UI Emoji */
@font-face {
  font-family: "EmojiArrow";
  src: local("Segoe UI Emoji"), local("Segoe UI Symbol");
  unicode-range: U+2195, U+FE0F; /* 匹配组合字符 */
}

/* 应用到编辑器 */
[contenteditable] {
  font-family: "NormalArrow", "EmojiArrow", sans-serif;
}
```

https://github.com/user-attachments/assets/855c306a-7345-481d-96ee-500773a0697c

### Describe the optimal solution

。
