### ISSUE TITLE
选中文本转换为行级代码，后面的文本消失

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#14705]
导入这个文档：[2025-04-25 15_48_31.sy.zip](https://github.com/user-attachments/files/19911514/2025-04-25.15_48_31.sy.zip)

使用这个字体 CSS：

```css
@font-face {
  font-family: "空山楷+常规";
  font-style: normal;
  src: url("plugins/custom-fonts/空山楷+常规.ttf");
}

:root {
  --b3-font-family: "空山楷+常规", "Helvetica Neue", "Luxi Sans", "DejaVu Sans", "Hiragino Sans GB", "Microsoft Yahei", "sans-serif","Twitter Emoji","Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji", "Segoe UI Symbol", "Android Emoji", "EmojiSymbols" !important;
}
```

字体文件发 QQ 了，需要下载了放置到对应位置

选中 `utils.py` 转换为行级代码（按F5刷新能恢复正常）：

https://github.com/user-attachments/assets/f99d5fab-8e96-4117-bdef-01d49c2c8713
