### ISSUE TITLE
Allow customizing fonts for headings and code blocks

### ISSUE THREAD

**Issue by HumbeBee** [siyuan-note/siyuan#14747]
### In what scenarios do you need this feature?

In other note-taking apps, they support separate fonts for headings and monospace content. This provides a much better experience for both reading and taking notes.
It would be great if SiYuan could implement this feature as well.

### Describe the optimal solution

For example, Bear app allows users to set different fonts for headings and code blocks, which greatly improves readability and visual structure.
Here's a screenshot of the relevant setting:
<img width="485" alt="Image" src="https://github.com/user-attachments/assets/71213110-0ae9-420d-8b08-0d84a039fe2d" />

**Comment by TCOTC** [comment]
You can use CSS snippets:

```css
/* heading block */
[data-type="NodeHeading"] {
    font-family: "Emojis Additional", "Emojis Reset", "CUSTOM FONT", sans-serif, emojis;
}
/* code block */
[data-type="NodeCodeBlock"] .hljs {
    font-family: "Emojis Additional", "Emojis Reset", "CUSTOM FONT", sans-serif, emojis;
}
```

![Image](https://github.com/user-attachments/assets/f8a0b19f-f134-4f3e-a36b-3272331f9591)
