### ISSUE TITLE
面包屑没有文本时需要隐藏 `.protyle-breadcrumb__text` 元素

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#14771]
### 问题

面包屑图标的右侧会稍微宽一点点，让我强迫症犯了：

![Image](https://github.com/user-attachments/assets/d4e90912-c122-4dbf-8f6c-ab4d1e1234dd)

![Image](https://github.com/user-attachments/assets/d867286d-38aa-4932-8dff-f3d2647c5318)

### 方案

两个方案：

1. 使用 CSS：

   ```css
   .protyle-breadcrumb__text:empty {
     display: none;
   }
   ```

2. `.protyle-breadcrumb__text` 元素中没有文本时直接移除 `.protyle-breadcrumb__text` 元素
