### ISSUE TITLE
能否去掉侧边栏的最小宽度限制？

### ISSUE THREAD

**Issue by KnIfER** [siyuan-note/siyuan#14881]
### In what scenarios do you need this feature?

拖拽resize侧边栏时，宽度缩小到屏幕四分之一，就不能继续减小了，很不爽。

这应该是vscode的设计吧，希望能改掉。不想在别的应用里也体验vscode的缺陷。

另外拖动改变大小时，这个margin边时大时小，文字还动来动去，不听号令~

视频1：drag-resize 侧边栏，最小允许的宽度，仅为屏幕的四分之一，太arbitrary
。

https://github.com/user-attachments/assets/a4af8872-eba0-4c80-a2e5-d62a217b0dad

视频2：margin边时大时小

https://github.com/user-attachments/assets/40ce0df8-8b7e-4fdd-96aa-fc7c36407231

希望能改进以上两处设计，谢谢。

### Describe the optimal solution

1. 侧边栏，最小允许宽度 === 10px
2. margin边固定大小，允许自定义，毕竟这个叫做响应式，但用户的屏幕大小是固定的，无需过分响应。

**Comment by KnIfER** [comment]
2  自适应宽度 问题解决了。

1 这要等下个版本吗，期待！

**Comment by KnIfER** [comment]
已充电，快改！orz

**Comment by wish5115** [comment]
> 1. [@Vanessa219](https://github.com/Vanessa219) 要不侧栏拖拽的 JS 就不限制到 `width: 232px;` 了，改用 CSS 限制侧栏 `min-width: 232px;`，有需要的用户可以用代码片段覆盖掉 min-width（p.s. 有空的话顺便把 [汇总：侧栏宽度问题 #14856](https://github.com/siyuan-note/siyuan/issues/14856) 这个问题也看一下）
> 2. [@KnIfER](https://github.com/KnIfER) 在设置里关闭“自适应宽度”，然后在集市里安装“[编辑器宽度](https://github.com/frostime/siyuan-center-width)”插件

只要选择符优先级更高，限宽也失效，详见宽屏代码

https://ld246.com/article/1746079460404#%E4%BB%A3%E7%A0%81

**Comment by wish5115** [comment]
> 我没能看懂

抱歉发错了，那个是编辑器的

**Comment by TCOTC** [comment]
@Vanessa219 我觉得我的方法是比较合理的，既不影响正常用户，又能满足特殊需求

**Comment by Vanessa219** [comment]
这样的话，每次点击这些按钮就不方便，需要滚动到右侧
![Image](https://github.com/user-attachments/assets/7ed0cd1d-438b-47cf-b3ba-d419200e422a)

**Comment by TCOTC** [comment]
不影响一般用户就行了，需要侧栏宽度很小的用户可以自己克服一下问题

**Comment by Vanessa219** [comment]
始终有一部分用户无法满足需求，而且在边界出现滚动条会很不好看。没有好的解决方案前就保持现状吧。

![Image](https://github.com/user-attachments/assets/4900931d-ef3a-4239-86c9-ce1f3842cff5)

**Comment by TCOTC** [comment]
https://ld246.com/article/1749350441486

**Comment by ouyang7923** [comment]
调大调小大家自由设定，老是说小了有的用户没法看。这是什么思维嘛。嫌小的用户不会调大吗，现在关键问题是不能调小。

**Comment by TCOTC** [comment]
看到有 CSS 的[方法](https://ld246.com/article/1749350441486/comment/1749353587784#comments)，我改了一下，现在可以通过 CSS 来实现自定义最小宽度了。

添加下面的 CSS 代码片段，然后双击拖拽调整侧栏宽度的那条线，就会自动缩小到自定义的最小宽度：

```css
.file-tree {
    flex: 0 0 auto;
}
:is(.layout__dockl, .layout__dockr):is([style*="width: 232px"], [style*="width: 320px"]) {
    min-width: 150px;
    max-width: 150px;
}
```

**Comment by ouyang7923** [comment]
> 看到有 CSS 的[方法](https://ld246.com/article/1749350441486/comment/1749353587784#comments)，我改了一下，现在可以通过 CSS 来实现自定义最小宽度了。
> 
> 添加下面的 CSS 代码片段，然后双击拖拽调整侧栏宽度的那条线，就会自动缩小到自定义的最小宽度：
> 
> .file-tree {
>     flex: 0 0 auto;
> }
> :is(.layout__dockl, .layout__dockr):is([style*="width: 232px"], [style*="width: 320px"]) {
>     min-width: 150px;
>     max-width: 150px;
> }

会有问题

![Image](https://github.com/user-attachments/assets/01b83ac1-e720-4ee0-9ccb-e0a084caf954)
这块会消失，只能用
```bash
:is(.layout__dockl, .layout__dockr):is([style*="width: 232px"], [style*="width: 320px"]) {
    min-width: 150px;
    max-width: 150px;
}
```

**Comment by TCOTC** [comment]
刚刚发现宽度有点问题，这样就行了：

```css
.file-tree {
    flex: 1 0 auto;
}
:is(.layout__dockl, .layout__dockr):is([style*="width: 232px"], [style*="width: 320px"]) {
    min-width: 150px;
    max-width: 150px;
}
```

https://github.com/user-attachments/assets/276229fc-1d19-4b9c-9524-09db263a9b32
