### ISSUE TITLE
在块引用元素后继续创建块引用，元素会异常合并

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#14985]
https://github.com/user-attachments/assets/0152e02d-98fd-4078-aca7-362554a43a50

用 CSS 改了下样式，方便判断：

```css
/* 用[ ]包裹引用文本 CSS片段 （Savor主题自用）*/
/* 排除闪卡、搜索界面，提高兼容性 */
.protyle:not(.card__block):not(.search__preview) > .protyle-content .protyle-wysiwyg [data-node-id] span[data-type*="block-ref"]:not([data-type="virtual-block-ref"]):not([data-type*="sup"]):not([data-type*="sub"]):not(.av__celltext--ref)::before {
  content: "[[";
  color: #a7abb3ca;
  pointer-events: none; /* 让括号不可点击 */
}
.protyle:not(.card__block):not(.search__preview) > .protyle-content .protyle-wysiwyg [data-node-id] span[data-type*="block-ref"]:not([data-type="virtual-block-ref"]):not([data-type*="sup"]):not([data-type*="sub"]):not(.av__celltext--ref)::after {
  content: "]]";
  color: #a7abb3ca;
  pointer-events: none; /* 让括号不可点击 */
}
/* 覆盖Savor主题原样式 */
.protyle-wysiwyg [data-node-id] span[data-type*="block-ref"]:not([data-type="virtual-block-ref"]):not([data-type*="sup"]):not([data-type*="sub"]):not(.av__celltext--ref) {
  font-size: 100%;
  color: #6456e6;
  background-color: #00000000;
  border-bottom: 0px dashed var(--b3-theme-on-surface);
}
```
