### ISSUE TITLE
划选时会向上全选

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#14993]
### In what scenarios do you need this feature?

使用 CSS 片段：

```css
.protyle-wysiwyg [data-node-id] {
    margin-top: 40px !important;
    margin-bottom: 40px !important;
}
```

在这行代码把选中的首个块设为了文档的首个块：

https://github.com/siyuan-note/siyuan/blob/d6f1296dd1b2beaa6f2e4ebd3b8c13deaba72d22/app/src/protyle/wysiwyg/index.ts#L1012

录屏演示：

https://github.com/user-attachments/assets/13bd6ced-f726-48bb-aff5-ee21867e494f

### Describe the optimal solution

。
