### ISSUE TITLE
数据库：卡片中的字段需要添加 hover 样式

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#15065]
https://github.com/siyuan-note/siyuan/issues/10414

参考 Notion：

https://github.com/user-attachments/assets/a8b02f9f-57de-4073-9e10-6a65885462fa

**Comment by Vanessa219** [comment]
感觉没有必要吧

**Comment by TCOTC** [comment]
比如这样就能判断主键的边界在哪，方便点击修改锚文本：

![Image](https://github.com/user-attachments/assets/906d5224-09f0-48fc-8e81-6e76413e6bed)

**Comment by Vanessa219** [comment]
hover 是整个元素，编辑还是需要点击padding 里面的。

**Comment by TCOTC** [comment]
还是觉得 hover 字段有背景色更好看，至少在编辑的时候会方便一点：

```css
.av__gallery-fields--edit .av__cell:hover {
  background-color: var(--b3-list-hover);
  border-radius: var(--b3-border-radius);
}
```

https://github.com/user-attachments/assets/760e2a97-88dd-4080-9685-e1d9e517b91d
