### ISSUE TITLE
数据库 achieved 功能

### ISSUE THREAD

**Issue by AiurQIAN** [siyuan-note/siyuan#15137]
### In what scenarios do you need this feature?

当创建了很多个数据库时， 在添加新的数据到数据库里的时候，会在很多数据库中进行选择
![Image](https://github.com/user-attachments/assets/e1fa3d72-955f-4729-8506-69d226e231e7)

### Describe the optimal solution

是否能增加数据库 achieve 功能， 数据库 achieve 以后只能 read， 同时也可以在添加中隐藏

### Describe the candidate solution

N.A

### Other information

N.A

**Comment by TCOTC** [comment]
听起来有点奇怪，输入关键词筛选一下应该就行了吧。

---

可以用下面这个 CSS 隐藏特定的数据库：

```css
/* data-block-id 后面填数据库块的 ID */
#commonMenu .b3-list-item[data-av-id][data-block-id="20240519164045-8lc898v"] {
  display: none;
}
```
