### ISSUE TITLE
修改面包屑部分样式会导致输入时卡死

### ISSUE THREAD

**Issue by zqhjl** [siyuan-note/siyuan#3384]
### 描述问题 Describe the problem

修改面包屑样式时，会导致输入时卡死，只能通过任务管理器结束任务。并且，该问题还分为以下两种情况：

- 直接将`.protyle-breadcrumb`的高度写死，就会出现问题，而修改`padding`时则没有问题，代码如下
```css
.protyle-breadcrumb {
  // padding: 10.5px 8px;  
  height: 45px;
}
```
- 修改`.protyle-breadcrumb .block__icon`的`margin`属性，也会出现该问题，而如果只使用`margin-right`或者换成`transform`则无问题，代码如下：
```css
.protyle-breadcrumb .block__icon {
    // margin-right: 6px;
    // transform: translateX(-6px) translateY(8.5px);
    margin: 8.5px 6px 0 0;
}
```

### 期待的结果 Expected result

我已经找到不会出现问题的替代方案，不过还是想问下为什么会出现这个问题…

### 截屏或者录屏演示 Screenshot or screen recording presentation

![卡死](https://user-images.githubusercontent.com/61345763/141075370-0304edde-2234-430c-975a-9ad53bff23c7.gif)

### 版本环境 Version environment

* Version: 1.5.0
* Operating system: Windows 10
* Browser (if used): 

### 日志文件 Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/7510916/siyuan.log)
