### ISSUE TITLE
Docker部署版本，获取lute.min.js失败而无法进入系统

### ISSUE THREAD

**Issue by nicollcheng** [siyuan-note/siyuan#3471]
### 描述问题 Describe the problem

输入授权码后一直卡在下图页面

![image](https://user-images.githubusercontent.com/64319004/142966809-9d758f9d-89f8-4b50-9d95-e69983374de4.png)

查看浏览器控制台，发现无法获取到lute.min.js文件

### 期待的结果 Expected result

输入授权码后应顺利进入系统

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/64319004/142966731-bdf20bbd-317b-4777-b95e-b2fcd24567d4.png)

![image](https://user-images.githubusercontent.com/64319004/142966809-9d758f9d-89f8-4b50-9d95-e69983374de4.png)

### 版本环境 Version environment

* Version: b3log/siyuan
* Operating system: Docker Server 20.10.10
* Browser (if used): Chrome

### 日志文件 Log File

docker容器中无错误日志输出

**Comment by 88250** [comment]
请贴一下 Docker 启动命令。

**Comment by nicollcheng** [comment]
刚刚的问题是因为servePath未修改导致的，但servePath修改后进入系统后，容器日志中出现异常信息，如下
```
2021/11/23 11:33:28 [Recovery] 2021/11/23 - 11:33:28 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:221 (0x4535a6)
/usr/local/go/src/runtime/signal_unix.go:735 (0x453576)
/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:1184 (0xc44946)
/go/pkg/mod/github.com/88250/melody@v0.0.0-20201115062536-c0b3394adcd1/melody.go:172 (0xc4492e)
/go/pkg/mod/github.com/88250/melody@v0.0.0-20201115062536-c0b3394adcd1/melody.go:161 (0x102b717)
/go/src/github.com/siyuan-note/siyuan-src/kernel/server/serve.go:195 (0x102b6dd)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0xc38bec)
/go/pkg/mod/github.com/gin-contrib/sessions@v0.0.3/sessions.go:52 (0xc38bd8)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0xffbb4c)
/go/pkg/mod/github.com/gin-contrib/gzip@v0.0.3/handler.go:60 (0xffbb22)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0xc2fea1)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99 (0xc2fe8c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0xc2ed5d)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489 (0xc2e9e5)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445 (0xc2e544)
/usr/local/go/src/net/http/server.go:2878 (0x75a99a)
/usr/local/go/src/net/http/server.go:1929 (0x756047)
/usr/local/go/src/runtime/asm_amd64.s:1581 (0x470940)
```
前端页面显示如下
![image](https://user-images.githubusercontent.com/64319004/142967830-5a1e11ea-7454-4387-ac61-7402aa31908c.png)

docker-compose.yaml文件如下：
```
version: '3'

services:
  siyuan:
    image: b3log/siyuan
    container_name: siyuan
    restart: always
    volumes:
      - ./workspace:/root/siyuan
    command: [--resident=true,--workspace=/root/siyuan,--ssl=true,--accessAuthCode=password,--servePath=nicollcheng.cn]
    network_mode: "host"
```

请问这是什么情况呢
