### ISSUE TITLE
Add toggle dropdown menu written in HTML like notion and notable

### ISSUE THREAD

**Issue by AShao0425** [siyuan-note/siyuan#3759]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
I heavily used notion before I reached into siyuan note, there is a quite nice feature in notion called `toggle listing`, it's a feature that users can specify additional details that the user can open and close on demand, it provides a summary near the toggle, when we click on the toggle the rest of the details exposes, as the image shown below, this is a nice feature since when some users like students (me) are summarizing questions, they are able to create questions easily and toggle open the answer with this feature.
![toggle](https://user-images.githubusercontent.com/79273649/148298167-a1d362f1-5779-4d1f-8b4d-b396290f407a.gif)

### 描述可能的最优解决方案 Describe the optimal solution
I don't know how notion works, I inspected their source code using chrome's built-in feature, they had a ton of `<div>` tags, but I do think it is achievable in a more easy way by using `<details>` and `<summary>` tags, since I know siyuan is built on electron. I had my own style written in one of my project before and it actually works quite nicely, here is the source code and the preview.

The `HTML` code,
```html
<details>
  <summary>Summary</summary>
  <!--Here is where you will insert text content-->
</details>
```

The `CSS` code,
```css
details {
  width: 50%;
  margin: 0 auto ;
  background: #282828;
  margin-bottom: .5rem;
  box-shadow: 0 .1rem 1rem -.5rem rgba(0,0,0,.4);
  border-radius: 5px;
  overflow: hidden;
  color: #fff;
}

summary {
  padding: 1rem;
  display: block;
  background: #333;
  padding-left: 2.2rem;
  position: relative;
  cursor: pointer;
  color: #fff;
}

summary:before {
  content: '';
  border-width: .4rem;
  border-style: solid;
  border-color: transparent transparent transparent #fff;
  position: absolute;
  top: 1.3rem;
  left: 1rem;
  transform: rotate(0);
  transform-origin: .2rem 50%;
  transition: .25s transform ease;
}

/* THE MAGIC 🧙♀️ */
details[open] > summary:before {
  transform: rotate(90deg);
}


details summary::-webkit-details-marker {
  display:none;
}

details > ul {
  padding-bottom: 1rem;
  margin-bottom: 0;
}
```

It provides a rotatable toggle style in side the `<summary>` tag, here's the preview,
![toggle](https://user-images.githubusercontent.com/79273649/148298286-c5228b96-0cd6-41cf-8128-111e595a9232.gif)

But the **BUG** with this is the indentation in the `<detail>` tags might not be adjusted to the edge of the box when you put `<p>` tags or heading tags in, the listing tags are fine, here's the preview, I'm not a webdev so I don't know how to fix this.
![image](https://user-images.githubusercontent.com/79273649/148297424-0471bc24-4091-4538-9160-21736c05fabc.png)

For rendering the math, I used mathjax instead of katex, here is a complete source code reference,
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <title>Test summary and details with animated tags</title>
    <script>
        MathJax = {
          tex: {
            inlineMath: [['$', '$'], ['\\(', '\\)']],
            displayMath: [['$$','$$'], ['\\[', '\\]']],
            processEscapes: true,
            processEnvironments: true
          },
          options: {
            skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre']
          }
        };
        
        window.addEventListener('load', (event) => {
            document.querySelectorAll("mjx-container").forEach(function(x){
              x.parentElement.classList += 'has-jax'})
          });
        
      </script>
      <style>
        details {
          width: 50%;
          margin: 0 auto ;
          background: #282828;
          margin-bottom: .5rem;
          box-shadow: 0 .1rem 1rem -.5rem rgba(0,0,0,.4);
          border-radius: 5px;
          overflow: hidden;
          color: #fff;
        }
        
        summary {
          padding: 1rem;
          display: block;
          background: #333;
          padding-left: 2.2rem;
          position: relative;
          cursor: pointer;
          color: #fff;
        }
        
        summary:before {
          content: '';
          border-width: .4rem;
          border-style: solid;
          border-color: transparent transparent transparent #fff;
          position: absolute;
          top: 1.3rem;
          left: 1rem;
          transform: rotate(0);
          transform-origin: .2rem 50%;
          transition: .25s transform ease;
        }
        
        /* THE MAGIC 🧙♀️ */
        details[open] > summary:before {
          transform: rotate(90deg);
        }
        
        
        details summary::-webkit-details-marker {
          display:none;
        }
        
        details > ul {
          padding-bottom: 1rem;
          margin-bottom: 0;
        }
      </style>
</head>
<body>
    <details>
        <summary>Evaluate the series $\sum_{n=1}^{\infty} \frac{1}{n(e^{2\pi n}-1)}$</summary>
        $$
        \frac{1}{n(e^{2\pi n}-1)}=\sum_{k=0}^\infty \frac{e^{-2 \pi  (k+1) n}}{n}
        $$

        $$
        \sum_{n=1}^\infty \frac{e^{-2 \pi  (k+1) n}}{n}=\log \left(1-e^{-2 \pi  (k+1)}\right)
        $$

        So, now, you need to compute,

        $$
        \sum_{k=0}^\infty \log \left(1-e^{-2 \pi  (k+1)}\right)
        $$
    </details>
</body>
</html>
```
The javascript code in between the `<head>` tags are for inline math rendering, solution provided by [official mathjax](mathjax.org) site, and this style is **not responsive on mobile view**.

Here are the two main issues at the moment,
<blockquote>
<ol>
  <li>Not responsive on mobile view</li>
  <li>Text indentation</li>
</ol>  
</blockquote>

Under siyuan's design, I suggest the developers design it like this,
1. when user type in `/toggle` a small rectangular window pop out like all the others to let user confirm.
2. then a window pop out like math block feature, but instead, two separate window pop out, one for `<summary>` tag one for `<detail>` tag, summary tag is a relatively smaller window, detail is a larger one.
3. the small summary window allow users to input what they want to have inside, the huge detail window is for user to but the huge issue is, how will the developers allow user to add inline element inside the window like math block, bold and etc.
4. Dark mode and light mode supported, in my source code, only dark mode is supported.

(ps: I'll post a design detail if necessary later here using photoshop for more explicit explanation.)

### 描述候选的解决方案 Describe the candidate solution
The candidate solution is just to reference the notion official site's style, but I don't understand a single thing there. 🤣.

### 其他信息 Other information
Operating environments are provided below,
<blockquote>
<ol>
  <li>Version: latest</li>
  <li>Operating system: Windows 10 Enterprise</li>
  <li>Browser (if used): Edge</li>
</ol>  
</blockquote>
