### ISSUE TITLE
docker 1.6.3 启动报错

### ISSUE THREAD

**Issue by wxlost** [siyuan-note/siyuan#3778]
使用root用户。进行docker-compose.yml启动。
```
version: '3'

services:
  siyuan:
    image: b3log/siyuan:latest
    container_name: siyuan
    restart: always
    volumes:
      - /home/siyuan/data:/home/siyuan/Documents/SiYuan
    command: [--resident=true,--workspace=/home/siyuan/Documents/SiYuan,--ssl=true,--accessAuthCode=xxxxxx,--servePath=xxx.xxx.com]
    network_mode: "host"
```

报错信息如下
```
siyuan    | 2022/01/07 16:32:05 create conf folder [/home/siyuan/Documents/SiYuan/conf] failed: mkdir /home/siyuan/Documents/SiYuan/conf: permission denied
siyuan exited with code 1
```
手动创建缺少的目录，能执行，到访问首页会卡在
```
If the dialog do not disappear automatically after 7 seconds, please close the window and restart.

If the problem still occurs after restarting, please report it via GitHub Issues, thank you!
```
同时在conf目录下也没有任何文件生成
