### ISSUE TITLE
代码块编辑时不闪烁代码语言和复制按钮

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#3962]
### 描述问题 Describe the problem

现在的代码块如果鼠标悬浮在代码块上，并开始编辑，右上方的代码语言和复制块就会一直闪烁。如果是代码块较长时就不可避免的闪烁
![思源代码块闪烁](https://user-images.githubusercontent.com/60436214/151699177-a3188d5e-9577-4573-9b09-c2e4935f0f65.gif)

1.7.6之前我是通过自定义主题，来实现代码块编辑时不闪烁的，但思源1.7.6之后，不能再对基本块使用:focus-within，该方法就失效了
所以想问官方有无计划改进
```css
.code-block:focus-within .protyle-icons .protyle-action__copy{
    opacity: 0;
}
.code-block .protyle-icons .protyle-action__copy:hover{
    opacity: 1;
}
```

### 版本环境 Version environment

* Version: 1.7.9
* Operating system: win10
