### ISSUE TITLE
Run Siyuan on Kubernetes issue

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#3969]
### 描述问题 Describe the problem

The app stuck on this page after login

![image](https://user-images.githubusercontent.com/33789516/151835132-8ababa11-b3c0-4006-8237-5d4c6cc90c2d.png)

![image](https://user-images.githubusercontent.com/33789516/151833062-999dcced-5e23-482c-8d21-0ecfd98afe6c.png)

---

### Info

Note: the URL is redirected to https://domain.com/stage/build/desktop/?r=hbo5tsm

![image](https://user-images.githubusercontent.com/33789516/151832846-43c1289d-0404-49bb-9780-40bc507428ba.png)

![image](https://user-images.githubusercontent.com/33789516/151834748-d45359ed-8f7d-4131-b34d-28a7e84d983c.png)

---

This is the Deployment code.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: siyuan-note
  namespace: default
  labels:
    app: siyuan-note
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siyuan-note
  template:
    metadata:
      labels:
        app: siyuan-note
    spec:
      containers:
      - name: siyuan
        image: b3log/siyuan:v1.7.10
        command: [ "/bin/sh", "-c", "--" ]
        args: ["/opt/siyuan/kernel -accessAuthCode '123456' -resident -workspace /siyuan/data"]
        ports:
        - containerPort: 6806
        volumeMounts:
          - name: siyuan-note-data
            mountPath: /siyuan/data 
          # - name: siyuan-note-conf
          #   mountPath: /siyuan 
      volumes:
        - name: siyuan-note-data
          persistentVolumeClaim:
            claimName: siyuan-note-data-claim
        # - name: siyuan-note-conf
        #   persistentVolumeClaim:
        #     claimName: siyuan-note-conf-claim
```
