### ISSUE TITLE
custom.css 编辑或通过外观设置修改后自动刷新

### ISSUE THREAD

**Issue by lkk66** [siyuan-note/siyuan#4069]
### 使用自定义主题的时候，修改了生成了custom.css，再次打开软件不会加载自定义的css

在自定义的css里面增加了一些样式，修改后可以实现软件样式的变化。但是再次打开软件后，不会加载增加的css样式，需要再去对custom.css进行保存一下样式才能变化

**Comment by 88250** [comment]
使用的是默认主题吗？

**Comment by 88250** [comment]
打开这个选项：设置 - 外观 - 自定义当前主题

**Comment by 88250** [comment]
思源版本是最新版么？我刚刚在 v1.8.2 上面没能重现这个问题。

**Comment by lkk66** [comment]
是最新版，1.8.2。是我新增的方式不对吗？

```css

/* PDF */
.textLayer,
.pdf__resize {
    mix-blend-mode: darken;
}

/* 自定义加粗样式 */
strong {
    font-weight: bold;
    font-size: 17px!important;
    font-weight: bold!important;
}

/* 自定义引用样式 */
.protyle-wysiwyg .bq {
    border-left: 0.25em solid #42b983;
    background-color: #f0f0f0;
}
```

我是在最下边增加的。修改后样式可以实时变化，但是重新打开软件后,他就不加载我定义的css了。我是写到:root外的，单独写到最下边的
