### ISSUE TITLE
`highlight.js` 的 `CSS` 样式中 `小括号内的字符串` 解析错误

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4480]
### 描述问题 Describe the problem

有下面的一个 CSS 代码块, 正常渲染高亮时应先闭合 `"` 再闭合 `)`, 但是 `highlight.js` 却先闭合 `)`, 导致之后的字符全部渲染错误
```css
: root {
    --custom-background-image: url("/appearance/themes/Dark+/image/background (01).jpg");
    --custom-background-image: url("/appearance/themes/Dark+/image/background (02).jpg");
}
```

![image](https://user-images.githubusercontent.com/49649786/161417867-1742a299-e819-4532-acf2-97cb9960bdbb.png)

### 期待的结果 Expected result

对于 `()` 内的字符串, 先闭合 `""` 后闭合 `()`

### 版本环境 Version environment

* Version: 1.9.6
