### ISSUE TITLE
改进代码块行号自适应

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4651]
### 描述问题 Describe the problem

REF: [v0.7.3 版本代码行号显示错误 · Issue #15 · Zuoqiu-Yingyi/siyuan-theme-dark-plus](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/issues/15)

经过测试发现为原生主题样式问题
![image](https://user-images.githubusercontent.com/49649786/164191113-1c2d138a-3b28-4f66-9589-a9d5cbb022c6.png)

由于代码块行号栏宽度固定, 导致使用较大字号(36px)时行数超过 100 即出现换行

### 期待的结果 Expected result

调整代码行号与内容的宽度单位为 `em`, `2.5em` 宽度经测试在任意字号下都可以显示 9999 行以内的代码
```css
.protyle-linenumber__rows {
    width: 2.5em;
}
.protyle-linenumber {
    padding-left: calc(2.5em + 4px) !important;
}
```
![image](https://user-images.githubusercontent.com/49649786/164190602-fe35c55d-5443-4850-acd7-47b255997948.png)

### 版本环境 Version environment

* Version: 2.0.0-b1
