### ISSUE TITLE
顶部停靠栏与底部停靠栏图标多于一个时排列错误

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#5415]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

顶部停靠栏(`#dockTop`)与底部停靠栏(`#dockBottom`)图标多于一个时与侧边停靠栏(`#dockLeft`, `#dockRight`)一致, 纵向排列, 导致部分图标被遮挡

### 期待的结果 Expected result

顶部停靠栏(`#dockTop`)与底部停靠栏(`#dockBottom`)图标多于一个时应横向排列

```css
#dockTop .dock__item,
#dockBottom .dock__item {
  display: inline-block;
}
```

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/49649786/179048325-4328426f-40fc-40ce-87c4-f7603f087b1a.png)

### 版本环境 Version environment

```markdown
- Version: `2.0.27`
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无
