### ISSUE TITLE
Add Support YAML Formatter 

### ISSUE THREAD

**Issue by FelipoAntonoff** [siyuan-note/siyuan#5474]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

It would be interesting to support the YAML Formatter Online, it is very useful for us to use Siyuan to create the content, but then export to Hugo CMS or another system that supports Markdown + data markup using YAML Formatter within Markdown.

### 描述可能的最优解决方案 Describe the optimal solution

It would be interesting to have a YAML element, so we can put it in the header of documents that we need to use.

It would even be interesting to be created automatically, as it happens in Dendron, which already has a basic structure and when we edit the content already saved on the modified date.

Example of the base structure:
```yaml
---
id: 2504l8r4mq5mdcc4rdd3a3g
title: Markdown
desc: Markdown markup language
updated: 1658110534834
created: 1657930248346
---
```
With the use of YAML, it would even be interesting to use the tags to stay inside it sometimes, it also serves to pass data to Markdown to be used in other systems to publish the final content.
