### ISSUE TITLE
docker版本思源可以像pc端一样，可以切换工作空间目录

### ISSUE THREAD

**Issue by JCJC01** [siyuan-note/siyuan#6576]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

平时沟通不少用户有多个工作空间的需求
如 for 工作，for生活 for 协助，for 发布等等
相信这个也是当初c端支持自定义工作空间功能的原因之一
目前docker需要实现这个需求需要建多个docker
如果需要建多个docker，这样体验不好

### 描述可能的最优解决方案 Describe the optimal solution

docker版本能像pc端一样，可以切换工作空间

**Comment by terwer** [comment]
我觉得自定义目录映射可以解决。多写几个启动脚本目录映射道不同地方就行了。

    volumes:
      - ./workspace:/home/siyuan/Documents

**Comment by JCJC01** [comment]
大佬好，不能思源人均程序员啊

**Comment by JCJC01** [comment]
docker的时候已经自定义路径了，只是不能切换，需要docker几个思源

**Comment by terwer** [comment]
docker版本本来就是命令启动的，既然已经用了docker版本了。你不写脚本之前是启动的呀[手动狗头]，那既然已经写了脚本了，在加之一个参数也没什么难的吧。

我说的写几个脚本也不需要部署多个呀，只是启动的时候指定不配置文件。

docker compose -f my-config1.yml

docker compose -f my-config2.yml

...

**Comment by terwer** [comment]
其实你说的切换我举得也能做，但是会有个很大的问题是啥呢，docker的目录是虚拟的，在容器里面，不是系统的真实目录。

本来我们是把系统目录映射到容器，但是万一你切换的时候选择的目录是不在映射目录之内的，那么就把数据直接存在容器里面了，这样的话不方便数据迁移，docker容器也会越来越大，我觉得这才是要考虑的吧。

个人观点，仅供参考。

**Comment by JCJC01** [comment]
大佬，请赐教
我是用群晖可视化界面docker的
唯一用到命令的时候是-workplace/siyuan自定义数据文件路径
是在这个基础上加上去吗？如何切换？

**Comment by terwer** [comment]
多个容器建议使用 docker compose 。我不太喜欢 群晖 这种套件，喜欢自定义的。
docker compose 基本上一行命令启动。

docker-compose.yml

```
version: '3'
services:
  prd-note:
    stdin_open: true
    tty: true
    image: b3log/siyuan:v2.4.12
    container_name: prd
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6806:6806"
    environment:
      # 最好使用此设定时区，其它镜像也可以使用，也可以用"TZ=Asia/Shanghai"
      - "TZ=CST-8"
    volumes:
      - ./workspace:/home/siyuan/Documents
    restart: "no"
```
