### ISSUE TITLE
部署到Kubernetes之后不久就exited kernel

### ISSUE THREAD

**Issue by JrMarcco** [siyuan-note/siyuan#7183]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

将 SiYuan 部署到Kubernetes之后，Pod会不断重启。

部署配置siyuan.yaml如下：
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: siyuan
  labels:
    app: siyuan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siyuan
  template:
    metadata:
      labels:
        app: siyuan
    spec:
      containers:
      - name: siyuan
        image: b3log/siyuan:latest
        command: ["/bin/sh", "-c", "--"]
        args: ["/opt/siyuan/kernel -port=6806 -workspace=/siyuan/workspace"]
        ports:
        - containerPort: 6806
        volumeMounts:
        - name: siyuan-data
          mountPath: /siyuan/workspace
      volumes:
      - name: siyuan-data
        persistentVolumeClaim:
          claimName: siyuan-pvc
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: siyuan-pvc
spec:
  storageClassName: "siyuan"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: siyuan-pv
spec:
  storageClassName: "siyuan"
  volumeMode: Filesystem
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/jrmarcco/sy-workspace
---
apiVersion: v1
kind: Service
metadata:
  name: siyuan
spec:
  selector:
    app: siyuan
  ports:
  - port: 6806
    targetPort: 6806
    name: http-siyuan
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: siyuan-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - siyuan.jrmarcco.io
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: siyuan
spec:
  hosts:
  - siyuan.jrmarcco.io
  gateways:
  - siyuan-gateway
  http:
  - match:
    - uri:
        exact: /siyuan
    route:
    - destination:
        host: siyuan
        port:
          number: 6806
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: siyuan
spec:
  host: siyuan

```

### 期待的结果 Expected result

能在Kubernetes中正常启动访问

### 版本环境 Version environment

```markdown
- Version: 2.7.0
- Operating System: Ubuntu Server 22.04，
- Kubernetes: v1.26.1
- Istio: 1.16.1
```

### 日志文件 Log file

查看Pod日志显示如下：
```
E 2023/01/27 23:28:50 working.go:411: unzip pandoc failed: open /opt/siyuan/pandoc.zip: no such file or directory
I 2023/01/27 23:28:50 working.go:119: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/01/27 23:28:50 runtime.go:46: kernel is booting:
    * ver [2.7.0]
    * arch [amd64]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace]
I 2023/01/27 23:28:50 runtime.go:91: use network proxy [system]
I 2023/01/27 23:28:50 serve.go:111: kernel [pid=1] http server [127.0.0.1:6806] is booting
I 2023/01/27 23:28:50 conf.go:616: database size [43 MB], tree/block count [252/14141]
I 2023/01/27 23:28:50 working.go:157: kernel booted
I 2023/01/27 23:29:27 process.go:77: no active UI proc, exit kernel process now
I 2023/01/27 23:29:27 conf.go:395: exiting kernel [force=false, execInstallPkg=1]
I 2023/01/27 23:29:27 database.go:1026: closed database
I 2023/01/27 23:29:27 conf.go:731: cleared workspace temp
I 2023/01/27 23:29:27 conf.go:444: exited kernel

```
