### ISSUE TITLE
使用alt+点击块标折叠后，无法再次点击展开

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#7326]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

使用alt+点击块标折叠后，无法再次点击展开，需要在其他地方点击后才能展开。

### 期待的结果 Expected result

可以正常展开

### 截屏或者录屏演示 Screenshot or screen recording presentation

![块标错误折叠](https://user-images.githubusercontent.com/74853597/218031624-901eff95-ef12-448b-8c48-b951742af287.gif)

### 版本环境 Version environment

```markdown
- Version: 2.7.4
- Operating System:win 10 
- Browser (if used):
```

### 日志文件 Log file

无需日志

**Comment by 88250** [comment]
我这里测试无法重现。

**Comment by zxhd863943427** [comment]
需要重新打开文档才可以复现。这个触发并不十分稳定。

**Comment by zxhd863943427** [comment]
测试了一下，应该是保持块标不消失的情况下更容易触发。块标一旦消失，这个问题就修复了
![块标错误折叠](https://user-images.githubusercontent.com/74853597/218033509-4b01a125-b91e-4a93-865f-d37d1f9be0be.gif)

**Comment by zxhd863943427** [comment]
另外，刚刚发现还会出现双重块标

![双重块标](https://user-images.githubusercontent.com/74853597/218034045-110cb944-7266-48bc-80d1-f775747e0f19.gif)

**Comment by 88250** [comment]
我这里还是重现不了。

![issue](https://user-images.githubusercontent.com/873584/218051881-9626d6f3-dd55-4c88-9fcc-3ac8cf9ae905.gif)

**Comment by 88250** [comment]
麻烦从输入列表开始完整录屏看下。

**Comment by zxhd863943427** [comment]
经过观察，我发现你的折叠后的显示效果跟我的折叠效果并不一致。

我刚刚又测试了下，发现虽然已经切换回默认主题了，但是代码片段并没有全部关闭。在代码片段全部关闭后，折叠的情况就一模一样了，同时这个问题也没有出现了。

可能导致出问题的css片段见下

```css
/*迷你档*/
.protyle-wysiwyg [data-node-id].li>div:nth-child(2) {
    margin-top: -0.3em !important;
}
.protyle-wysiwyg [data-node-id].li>[data-node-id] {
    margin-left: 0.9em !important;
    padding-left: 1.1em;
}
.protyle-wysiwyg [data-node-id].li>.list {
    padding-left: 0em;
}
```
