### ISSUE TITLE
钉住的页签不再使用斜体

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#7404]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

思源里倾斜的页签是表示内容未修改会被新打开的页签替换 
但是钉住的页签已经不能被替换了，依然有重新打开软件emoji就会倾斜的问题
![image](https://user-images.githubusercontent.com/60436214/219937353-a57a2cbf-e417-4208-a94c-2ff7990626ad.png)

### 期待的结果 Expected result

钉住的页签重新打开软件后不倾斜
比如加一段css
```css
/* 钉住的页签不倾斜 */
.layout-tab-bar .item--pin.item--unupdate {
    font-style: normal;
    color: var(--b3-theme-on-surface);
}
```

### 版本环境 Version environment

```markdown
- Version: v2.7.5
- Operating System: Win11
- Browser (if used):
```

### 日志文件 Log file

无
