### ISSUE TITLE
挂件块导出内容支持预格式化文本

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#7753]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前挂件块设置块属性 `data-export-md` 中的内容会受到 <kbd>设置 > 导出</kbd> 中的配置项控制, 比如 `段落开头空两格`, 这会导致一些预格式化的文本(比如 YFM)出现错误, 因此希望有一个方案在导出 markdown 时可以原封不动得将一段文本插入对应的位置

### 描述可能的最优解决方案 Describe the optimal solution

增加挂件块数据导出属性 `data-export-plain` (或者叫 `data-export-pre` 也可以), 在导出时使用如下方案

| 挂件块存在的属性                                                    | 导出 `Markdown`                               | 导出 `HTML`                                                        |
| :------------------------------------------------------------------ | :-------------------------------------------- | :----------------------------------------------------------------- |
| `data-export-html`                                                  | 忽略                                          | 直接替换                                                           |
| `data-export-md`                                                    | 格式化后替换                                  | 格式化并渲染后替换                                                 |
| `data-export-plain`                                                 | 直接替换                                      | 使用 ```` ``` ```` 包围并渲染后替换                                |
| `data-export-html` <br/> `data-export-md` <br/> `data-export-plain` | 优先级 `data-export-md` > `data-export-plain` | 优先级 `data-export-html` > `data-export-md` > `data-export-plain` |

### 描述候选的解决方案 Describe the candidate solution

挂件块数据导出属性 `data-export-md` 中使用带特定标签的代码块围栏中的内容在导出 markdown 时删除围栏标志并保持原样插入, 下面是一个示例

`data-export-md` 中的内容为
````
这是一个段落块
```this-is-a-tag
---
这是一段
  - 预格式化
  - 文本
---
```
下面是一个列表块
- 列表块第一行
- 列表块第二行
````

导出的 markdown 文件中的内容为
```
这是一个段落块

---
这是一段
  - 预格式化
  - 文本
---

下面是一个列表块

* 列表块第一行
* 列表块第二行
```

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/227139184-48117296-9197-4954-a567-dea3c5e444d0.png)

**Comment by Zuoqiu-Yingyi** [comment]
如果 YAML 是如下所示的序列样式会怎么处理?
```yaml
---
title: foo
date: 2023-03-15T22:47:01Z
lastmod: 2023-03-22T18:23:30Z
tag:
- tag1
- tag2
---
```

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/227184987-4129cccf-c5d3-4c77-9772-a835f86ac2cc.png)

**Comment by Zuoqiu-Yingyi** [comment]
@88250 貌似还是没有解决问题, 如下所示的 YFM 被格式化后产生的缩进会导致语义发生更改

格式化前:
```yaml
---
Title: 文档块测试
name: "123"
alias:
  - 别名1
  - 别名2
date: 2023-03-28T13:06:46.000Z
---
```

格式化后:
```yaml
---

Title: 文档块测试
name: "123"
alias:

- 别名1
- 别名2
  date: 2023-03-28T13:06:46.000Z

---
```
