### ISSUE TITLE
思源笔记docker部署的时候端口好像不能自定义

### ISSUE THREAD

**Issue by sw554227643** [siyuan-note/siyuan#7856]
### In what scenarios do you need this feature?

因为不支持账号管理方式来管理笔记，所以如果有多人想创建私有笔记的时候好像没有办法通过创建多个docker应用来实现，请问有什么好的办法来实现这种功能吗

### Describe the optimal solution

下面是几个建议：
1、创建应用的时候能够自定义端口。
2、添加用户管理功能，使用账号区分工作空间。
3、如果以上功能无法实现，是否可以加入多个创作空间，通过切换创作空间来达到区分不同人的笔记的需求。

**Comment by terwer** [comment]
其实docker内部端口不用改呀，你多个实例，外部映射端口改一下就行了。
建议看看docker端口映射。
我目前就是部署多个实例，只需要改外部端口即可，给你参考

instancae1
```
version: '3'
services:
  prd-note:
    stdin_open: true
    tty: true
    image: terwer/my-note-docker-private:latest
    container_name: my-note-docker-private
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6807:6806"
    environment:
      # 最好使用此设定时区，其它镜像也可以使用，也可以用"TZ=Asia/Shanghai"
      - "TZ=CST-8"
    volumes:
      - ./workspace:/home/siyuan/Documents
    restart: "no"
```

instancae2

```
version: '3'
services:
  prd-note:
    stdin_open: true
    tty: true
    image: terwer/my-note-docker-test:latest
    container_name: my-note-docker-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6806:6806"
    environment:
      # 最好使用此设定时区，其它镜像也可以使用，也可以用"TZ=Asia/Shanghai"
      - "TZ=CST-8"
    volumes:
      - ./workspace:/home/siyuan/Documents
    restart: "no"
```

instancae3
```
version: '3'
services:
  prd-note:
    stdin_open: true
    tty: true
    image: terwer/my-note-docker:latest
    container_name: my-note-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6808:6806"
    environment:
      # 最好使用此设定时区，其它镜像也可以使用，也可以用"TZ=Asia/Shanghai"
      - "TZ=CST-8"
    volumes:
      - ./workspace:/home/siyuan/Documents
    restart: "no"
```

每个实例用不同文件夹就行了。
