### ISSUE TITLE
Improve block ref floating window size and position

### ISSUE THREAD

**Issue by Vanly7710** [siyuan-note/siyuan#8422]
### In what scenarios do you need this feature?

思源的原生悬浮窗十分好用，只是目前没有设置悬浮窗大小的选项，它的大小是自行动态计算的，这导致每次浮悬窗出现的大小都不固定，有时候明明悬浮窗内的内容很多，但是浮窗只显示一行大小，如下图所示
![image](https://github.com/siyuan-note/siyuan/assets/134844680/5eef8e8f-3bed-4125-b97b-f8e1528d2e97)

所以希望提供一些能够自行设置的“弹出悬浮窗占当前思源窗口的比例”，类似于这样的选项。

### Describe the optimal solution

如上所述

**Comment by 88250** [comment]
靠……靠插件不知道能不能实现。

**Comment by Vanly7710** [comment]
靠插件不知道有没有难度，我在其他软件上用过类似的浮窗插件，有一个最大的问题是对引用内容的位置定位不准确，比如引用的段落块它却定位跳转到这个段落块的标题上之类的

另外通过浮窗查看内容的操作，我个人认为还是蛮高频的。如果靠插件的话，那插件作者要时刻紧跟思源的编辑器更新，对开发者的时间要求会比较高

当然，我毕竟不会开发，以上只是我的一些推测，如果不对之处还望海涵。我把那个其他软件的插件链接放上来，也许有一些有用的参考：https://github.com/nothingislost/obsidian-hover-editor

这个插件的内部有提供以下这些选项
![image](https://github.com/siyuan-note/siyuan/assets/134844680/89c176a3-d838-4634-8ddf-3f6e84735125)

我的总体提议如上，祝大家六一快乐🥳

**Comment by BryceAndJuly** [comment]
通过CSS来设置弹窗的高度似乎有点作用：

```css
/* 悬浮——弹窗 */
.block__popover.block__popover--move.block__popover--open {
    max-height: 75vh !important;
    min-height: 70vh !important;
    width: 735px;
}
```

https://github.com/siyuan-note/siyuan/assets/58081876/e1c1f263-c2c5-4120-a486-b3af84f6b1c3
