### ISSUE TITLE
Add animation effects when inserting blocks into the database

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9092]

**Comment by zxhd863943427** [comment]
这个动画的目的是什么？老实说现在的效果有点奇怪，有点过度动画了。

**Comment by 88250** [comment]
减少卡顿感。



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 22, 2023 14:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Add animation effects when inserting blocksinto the database (Issue #9092)




 
这个动画的目的是什么？老实说现在的效果有点奇怪，有点过度动画了。

**Comment by zxhd863943427** [comment]
这个动画效果在属性视图里太突兀了，建议改成 骨架屏 Skeleton 的那种风格。

**Comment by Vanessa219** [comment]
那是什么风格？

**Comment by zxhd863943427** [comment]
就是这种效果：
![骨架屏](https://github.com/siyuan-note/siyuan/assets/74853597/c3ca8799-7a4f-4adf-b91e-d9494849b843)

**Comment by zxhd863943427** [comment]
动态有点卡，这是视频：

https://github.com/siyuan-note/siyuan/assets/74853597/e75b31db-4151-46e5-a17f-cc07b12206a6

**Comment by Vanessa219** [comment]
收到，稍后再改改

**Comment by zxhd863943427** [comment]
使用的css代码见下：
```css
.av__row.loading {
    background: linear-gradient( 100deg, rgba(255, 255, 255, 0) 40%, rgba(255, 255, 255, .5) 50%, rgba(255, 255, 255, 0) 60% ) var(--b3-theme-background-light);
    background-size: 200% 100%;
    background-position-x: 180%;
    animation: 1s loading ease-in-out infinite;
}
@keyframes loading {
  to {
    background-position-x: -20%;
  }
}
```
实际使用的背景色可能还要淡一点。
