### ISSUE TITLE
能否添加选项，由用户自行选择是否开启超级块的蓝色小符号

### ISSUE THREAD

**Issue by alphaleek** [siyuan-note/siyuan#986]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
我们将多个块合为一个超级块，不仅因为方便统一进行块引用，还因为这些内容具有更高的相关度。而删除超级块的蓝色小符号，则无法在文档中直接体现出这些内容的相关度

![image](https://user-images.githubusercontent.com/76611744/104007842-896d4d80-51e3-11eb-9287-3e10cf7f1efc.png)
![image](https://user-images.githubusercontent.com/76611744/104008030-d0f3d980-51e3-11eb-8b99-b171b57bc96c.png)

### 描述最优的解决方案 Describe the optimal solution
能否添加选项，由用户自行选择是否开启超级块的蓝色小符号

**Comment by 88250** [comment]
你好，稍后我们会再调整一下样式，标记符的逻辑尽量和其他 md 标记符一样，默认统一隐藏。

**Comment by Vanessa219** [comment]
可以通过自行定义 CSS 来解决

1. 依次点击设置->外观->主题->打开主题文件夹
2. 在当前主题的 custom.css 文件中添加
```css
div[data-type="super-block"] {
    border: 1px solid var(--b3-border-color);
}
```

如需进一步修改可参考帮助文档中的自定义外观一节
